### ISSUE TITLE
statedb design and implement

### ISSUE THREAD

**Issue by jolestar** [rooch-network/rooch#1]
- [x] smt library: implement a standalone smt library.
- [x] two-level smt state tree design and implement.
- [x] provide a mock storage
- [x] embed a local database(rocksdb?)

**Comment by wubuku** [comment]
RocksDB seems good, and there was a project named rocksplicator that implemented RocksDB's replication feature at https://github.com/pinterest/rocksplicator. 

But unfortunately, the project has been archived and there doesn't seem to be a successor.:(

**Comment by feliciss** [comment]
Hyperbee is like a local database solution: https://docs.holepunch.to/building-blocks/hyperbee.

**Comment by baichuan3** [comment]
close as completed via https://github.com/rooch-network/rooch/pull/454 and https://github.com/rooch-network/rooch/pull/523
