### ISSUE TITLE
[DA] data flow

### ISSUE THREAD

**Issue by popcnt-subodhi** [rooch-network/rooch#1031]
roles:

1. sequencer
2. da server
3. data visibility
4. da server backend 
5. L1
6. verifier
7. fraud proof process

goals:

1. performance enhancement by data visibility
2. high liveness by exposing da server bakcend
3. extrem compression on L1
4. easy to be verified in verifier
5. easy to be verified in fraud proof process

todo:
1. naming data availbility (data visibility?)
2. specification

https://github.com/rooch-network/rooch/issues/999

**Comment by popcnt-subodhi** [comment]
https://github.com/rooch-network/rooch/issues/999

**Comment by jolestar** [comment]
What does `data visibility` mean? Simplify the verifier and fraud-proof first. This roadmap goal is #1024.

**Comment by popcnt-subodhi** [comment]
> What does `data visibility` mean? Simplify the verifier and fraud-proof first. This roadmap goal is #1024.

A new concept introduced by my new blog（https://rooch.network/blog/triple-iron-curtains-before-da）. It emphasizes DA's ability to publish data from a L2 perspective and to be leveraged quickly

**Comment by popcnt-subodhi** [comment]
@bytedeveloperr You've been investigating celestia for a while now. celestia accesses files by namespace and id (not just by a hash/specified key), and I've got an initial idea of how to get into our DA services, and I'd like to hear your thoughts on it, either by commenting here or by opening a separate issue.

**Comment by bytedeveloperr** [comment]
I just created an issue @popcnt-subodhi. I think we should also look at your intitial idea, It could be much better than celestia's.

**Comment by jolestar** [comment]
Is this issue finished?

**Comment by popcnt-subodhi** [comment]
> Is this issue finished?

have been splited into several issues with more details. In general, it's done
