### ISSUE TITLE
cli and integration tests adapt context storage parameters

### ISSUE THREAD

**Issue by wow-sven** [rooch-network/rooch#107]
Error: RPC call failed: ErrorObject { code: ServerError(-32000), message: "failed to send message, ref is no longer valid", data: None }

Caused by:
    RPC call failed: ErrorObject { code: ServerError(-32000), message: "failed to send message, ref is no longer valid", data: None }

**Comment by jolestar** [comment]
Is this problem solved? The reason?

**Comment by baichuan3** [comment]
1) resolve_args when executing transaction
https://github.com/rooch-network/rooch/blob/3cdeed058a73b533f8edca1bf3643b047f691a7a/moveos/moveos/src/moveos.rs#L99-L118

2) resolver fills storage context
https://github.com/rooch-network/rooch/blob/3cdeed058a73b533f8edca1bf3643b047f691a7a/moveos/moveos/src/vm/tx_argument_resolver.rs#L55-L61

3) the cli call moveos server to execute transaction
```
        let txn = MoveTransaction::new_function(
            ModuleId::new(
                AccountAddress::new([
                    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                    0, 0, 0, 0, 0, 1,
                ]),
                ident_str!("account").to_owned(),
            ),
            ident_str!("create_account_entry").to_owned(),
            vec![],
            vec![bcs::to_bytes(new_address.0.as_bytes()).unwrap()],
        );
```

It means that you need to bring the storage context parameter in the cli to call the entry contract.

At the same time, after the introduction of the storage context, if some of the original read-only methods involve calling global_exist, global_borrow and other instructions, it means that the storage context also needs to be passed in.
