### ISSUE TITLE
[RPC] Support `eth_getCode` API

### ISSUE THREAD

**Issue by jolestar** [rooch-network/rooch#1092]
Some ETH wallets need the `eth_getCode` API 

```
2023-11-02T15:52:08.032956Z INFO connection{remote_addr=172.17.0.1:57066 conn_id=28}: rooch_rpc_server::service::rpc_logger: event="on_call" transport="http" method_name="eth_getCode" params="[\"0xd46e8dd67c5d32be8058bb8eb970870f07244568\",\"latest\"]"
2023-11-02T15:52:08.033339Z INFO connection{remote_addr=172.17.0.1:57066 conn_id=28}: rooch_rpc_server::service::rpc_logger: event="on_result" method_name="eth_getCode" success=false elapsed_millis=0
```

<img width="366" alt="Screen Shot 2023-11-02 at 23 55 56" src="https://github.com/rooch-network/rooch/assets/77268/c06eb903-b152-4e66-8a89-e7846804584f">

**Comment by bytedeveloperr** [comment]
is this supposed to return the code at the contract address on the underlying L1, or the move code at the corresponding rooch address?

**Comment by jolestar** [comment]
> is this supposed to return the code at the contract address on the underlying L1 blockchain, or the move bytecode at the corresponding rooch address?

We could try to return an empty hex string. I do not know how the wallet gets the address `0xd46e8dd67c5d32be8058bb8eb970870f07244568`. Maybe it is the rooch MoveAction BCS bytes prefix.

**Comment by bytedeveloperr** [comment]
yeah, maybe the wallet retained the first 20 bytes and cut the rest off...

and regarding the `eth_getCode` method, are we returning the underlying L1 contract code?

**Comment by jolestar** [comment]
> yeah, maybe the wallet retained the first 20 bytes and cut the rest off...
> 
> and regarding the `eth_getCode` method, are we returning the underlying L1 contract code?

We have no EVM code, and the address is not correct.

1. We can try to return the empty string first and test the wallet.
2. If it does not work, maybe we should use RLP to encode the MoveAction and simulate the call of the EVM contract.
