### ISSUE TITLE
Need to fix the error messages

### ISSUE THREAD

**Issue by geometryolife** [rooch-network/rooch#1093]
当我使用浏览器刷新，会出现这个错误提示：
![image](https://github.com/rooch-network/rooch/assets/54882546/b9ffc892-ed6b-40d0-991c-3dc6cdad91b7)
![image](https://github.com/rooch-network/rooch/assets/54882546/08fbedf5-2d81-4856-8144-77e09a283190)
用 Dashboard 的按钮刷新就是正常的：
![image](https://github.com/rooch-network/rooch/assets/54882546/f55f429f-79a6-4ad4-8f30-1982a449fa34)

**Comment by jolestar** [comment]
Is this bug resolved?

**Comment by geometryolife** [comment]
> Is this bug resolved?

Not yet.
