### ISSUE TITLE
The Rooch Move library collaborates with the Aptos Move library for development

### ISSUE THREAD

**Issue by stevenlaw123** [rooch-network/rooch#1135]
We need to discuss how to collaborate and develop Rooch Move and Aptos Move together.

Reference content:

https://aptoslabs.medium.com/the-future-of-move-at-aptos-17d0656dcc31

https://github.com/MystenLabs/sui/issues/14062

**Comment by stevenlaw123** [comment]
Currently, we have two approaches. We directly introduce the Aptos Move code as a Rust Package and then, together with them, we port the modified compiler and virtual machine features to the Aptos Move library.

However, our code has some invasive modifications for both the Move virtual machine and the compiler, so we cannot directly import and use the Aptos Move repository.

We can only add our enhanced features based on their code. The main areas include:

1. Compiling Move code using source code strings.
2. Related code for Custom TransactionDataCache.
3. Additional compilation functions added to check private_generics and other features in Move's integration and unit tests.

These functionalities need to be ported to the Aptos Move code and thoroughly tested after the porting process.

In the future, if Aptos Move adds new features, we will need to merge their code with ours

**Comment by jolestar** [comment]
#1231
