### ISSUE TITLE
rooch-framework/crypto base64

### ISSUE THREAD

**Issue by yubing744** [rooch-network/rooch#1161]
Base64 decoding needs to be implemented in the Move contract for JWT header and body decoding.

**Comment by jolestar** [comment]
Use a native function like https://github.com/rooch-network/rooch/blob/f7573bb942b956097e0d1f06a61770ee1f8c60f0/crates/rooch-framework/sources/crypto/decoding.move

Or use a pure Move implement:

https://github.com/movefuns/movefuns/blob/main/starcoin/sources/Base64.move

**Comment by feliciss** [comment]
> Use a native function like https://github.com/rooch-network/rooch/blob/f7573bb942b956097e0d1f06a61770ee1f8c60f0/crates/rooch-framework/sources/crypto/decoding.move

Is there a need for implementing the `base64` function in Move native functions?

**Comment by yubing744** [comment]
This PR implements Base64 using native functions.

https://github.com/rooch-network/rooch/pull/2553
