### ISSUE TITLE
[RPC] The RPC response format

### ISSUE THREAD

**Issue by jolestar** [rooch-network/rooch#117]
Currently the output message is:

```
Ok { code: Ok, message: None, data: Some("error") }
Ok { code: Ok, message: None, data: Some("ok") }
```

Need to define the usage scenario of `code`, `message` and `data`

**Comment by wubuku** [comment]
If using JSON RPC, there are standard specifications for both normal messages and error messages in JSON RPC itself, as seen here: https://www.jsonrpc.org/specification#error_object

**Comment by jolestar** [comment]
Remove the JsonResponse wrap in the Result
