### ISSUE TITLE
[RPC] Implement state api

### ISSUE THREAD

**Issue by jolestar** [rooch-network/rooch#12]
## REST Style

Ref AccessPath #58 

1. Get the item by access_path
   /$access_path
2. Retrieves items by access_path, if the item is a Table
   /$access_path/iter?start=1&end=100

## RPC Style 

TODO

### Dependency

#10

**Comment by wubuku** [comment]
Should we add an API to get events to the first milestone? In my experience, it is very necessary for developing off-chain services.

---

For example, let me use a demo that I have done before: https://github.com/dddappp/A-Aptos-Demo/

The Aptos Node API interfaces that off-chain Java services depend on are:

* [Get events by event handle](https://fullnode.devnet.aptoslabs.com/v1/spec#/operations/get_events_by_event_handle). Through this interface, you can obtain information about the creation of resource accounts, various domain events, etc.

* [Get account resource](https://fullnode.devnet.aptoslabs.com/v1/spec#/operations/get_account_resource). This interface is used to obtain resource information under an account. To obtain the handle of the Table that stores the aggregate root status, you need to use this interface.

* [Get table item](https://fullnode.devnet.aptoslabs.com/v1/spec#/operations/get_table_item). This interface is used to obtain the status of aggregate root entities (such as Order entities aggregated by orders) and internal entities (such as OrderItem, which aggregates the entities of order items inside the Order aggregate).

**Comment by jolestar** [comment]
> Should we add an API to get events to the first milestone? In my experience, it is very necessary for developing off-chain services.

event dependent on #91

**Comment by wubuku** [comment]
For the APIs of getting-state, the `Get table Item` interface is also a necessary basic interface. If I were an application developer, I would like to see it in the first milestone. 

Can refer to Aptos's interface: [Get table item](https://fullnode.devnet.aptoslabs.com/v1/spec#/operations/get_table_item)

**Comment by jolestar** [comment]
> For the APIs of getting-state, the `Get table Item` interface is also a necessary basic interface. If I were an application developer, I would like to see it in the first milestone.


The new `access_path` design is support retrieving table items.

**Comment by jolestar** [comment]
Resolved by #205 

We do not support retrieving items. Just support getting items with multi-keys. Let the iterable API TBD.
