### ISSUE TITLE
[security] Manage transaction size configurations in Move contracts.

### ISSUE THREAD

**Issue by stevenlaw123** [rooch-network/rooch#1249]
1. Set transaction size configurations in the system configuration contract and execute them in the genesis transaction. 

2. Retrieve transaction size information from the configuration contract during transaction validation. 

3. The sequencer can modify on-chain transaction size configurations through contract upgrades or by modifying the configuration items in the contract.

NOTE: the configuration of transaction size must be at least 4M.

**Comment by jolestar** [comment]
eval the max tx size @stevenlaw123

**Comment by jolestar** [comment]
We limit the tx size via the max gas amount. so we do not need another tx size config.

**Comment by jolestar** [comment]
Maybe we need a test case to ensure it. @steelgeek091
