### ISSUE TITLE
[CLI] Add `--gas-limit` option when sending transactions in CLI

### ISSUE THREAD

**Issue by pause125** [rooch-network/rooch#1257]
The current gas limit is 100_000_000, which is insufficient in certain situations. To allow users to customize the gas limit when sending transactions, an option "--gas-limit" should be added to the CLI command， like `rooch move run`, `rooch move publish`, etc.

**Comment by jolestar** [comment]
Add to the TransactionOptions.

https://github.com/rooch-network/rooch/blob/4691056cf30b66caf9a9050dc4f429e35c5b394a/crates/rooch/src/cli_types.rs#L70-L71
