### ISSUE TITLE
[document] Transaction Flow and Confirmation

### ISSUE THREAD

**Issue by jolestar** [rooch-network/rooch#126]
from #100 

Part of it describe in https://rooch.network/blog/modular-evolution-of-rollup-layer2

**Comment by wubuku** [comment]
I have roughly skimmed through this blog, and I think my understanding of Rooch should be mostly correct.

I may not have explained it too clearly before. When I referred to the simulation layer, it means that the same application can have two "transaction execution environments," one that is "simulated" and one that is the "real deal". The simulation environment may be "missing a few things" compared to the real environment, so the execution speed will be faster. The difference becomes more apparent when the modules in the real environment are "heavier" or have a larger workload.

Looking forward to a more detailed and comprehensive article.
