### ISSUE TITLE
[Framework] Token and NFT standard

### ISSUE THREAD

**Issue by jolestar** [rooch-network/rooch#13]
- [x] token standard https://github.com/rooch-network/rooch/issues/627
- [x] NFT standard https://github.com/rooch-network/rooch/issues/628
- [ ] multi-chain Token to Rooch Token mapping https://github.com/rooch-network/rooch/issues/626

**Comment by feliciss** [comment]
Any updates on this issue?

**Comment by jolestar** [comment]
Make #626 TBD
