### ISSUE TITLE
[ChainID] Refactor Rooch ChainID

### ISSUE THREAD

**Issue by jolestar** [rooch-network/rooch#1335]
Currently, we use the ChainID as follows:

https://github.com/rooch-network/rooch/blob/1273ba1b394ec8bedf4804568cc3d1310ddcf952/crates/rooch-types/src/chain_id.rs#L14-L17

This is to avoid conflict with ETH ChainID. But if we do not need to simulate as an ETH chain and use the sign message method to get the SessionKey and directly call Rooch RPC, we can redesign the ChainID.

```rust
pub const CHAIN_ID_LOCAL: u64 = 4;
pub const CHAIN_ID_DEV: u64 = 3;
pub const CHAIN_ID_TEST: u64 = 2;
pub const CHAIN_ID_MAIN: u64 = 1;
```

Or we use a Hash as the ChainID, the ChainID like an AppID.

**Comment by baichuan3** [comment]
Does this mean that it will no longer be considered as Layer 2 of ETH?

**Comment by jolestar** [comment]
> Does this mean that it will no longer be considered as Layer 2 of ETH?

We do not provide ETH PRC; we always use SessionKey to support multi-chain.
