### ISSUE TITLE
我想要在windows下进行cargo build，报错celestia-proto v0.1.0

### ISSUE THREAD

**Issue by wenna8031** [rooch-network/rooch#1348]
error: failed to run custom build command for `celestia-proto v0.1.0 (https://github.com/eigerco/celestia-node-rs.git?rev=129272e8d926b4c7badf27a26dea915323dd6489#129272e8)`

Caused by:
  process didn't exit successfully: `D:\work\work\JetBrains\project\rooch\target\debug\build\celestia-proto-83fe2a11728c79f1\build-script-build` (exit code: 101)
  --- stderr
  thread 'main' panicked at C:\Users\admin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\prost-build-0.12.3\src\lib.rs:1521:10:
  Could not find `protoc` installation and this build crate cannot proceed without
      this knowledge. If `protoc` is installed and this crate had trouble finding
      it, you can set the `PROTOC` environment variable with the specific path to your
      installed `protoc` binary.You can download it from https://github.com/protocolbuffers/protobuf/releases or from your package manager.

  For more information: https://docs.rs/prost-build/#sourcing-protoc

  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by templexxx** [comment]
You need to install protobuf tools firstly

**Comment by wenna8031** [comment]
谢谢

**Comment by popcnt-subodhi** [comment]
> 谢谢

fixed?
