### ISSUE TITLE
[Bitcoin] Introduce the bitcoin-ordinals integration tests framework into Rooch 

### ISSUE THREAD

**Issue by jolestar** [rooch-network/rooch#1352]
Introduce the bitcoin-ordinals integration tests framework into Rooch

https://github.com/ordinals/ord/tree/master/test-bitcoincore-rpc

**Comment by jolestar** [comment]
Make this TBD

**Comment by feliciss** [comment]
> Make this TBD

Got it.

**Comment by yubing744** [comment]
I am currently writing integration tests for bitseed, using the solution: testcontainers + cucumber. 

For specific implementation, please refer to: https://github.com/bitseed/bitseed/pull/17/files#diff-eb771f54a1fdc1c330a82981d7d27d1202a5cbe3a59581ff67af5e3361f5f90e

**Comment by yubing744** [comment]
Split the integration test part into a separate PR: https://github.com/bitseed/bitseed/pull/18

**Comment by jolestar** [comment]
Use another approach to finish this.
