### ISSUE TITLE
[CLI] Occurs "No such device or address" when open /dev/tty on Debian

### ISSUE THREAD

**Issue by baichuan3** [rooch-network/rooch#1385]
```
docker run --rm -v /root:/root ghcr.io/rooch-network/rooch:main init
```

Error occurs:
```
Rooch server config file generated at /root/.rooch/rooch_config/server.yaml
Creating client config file ["/root/.rooch/rooch_config/rooch.yaml"] with rooch native validator.
IO error: No such device or address (os error 6)
```

Ref: https://stackoverflow.com/questions/55631937/what-is-the-meaning-of-no-such-device-or-addresserror-code-6

**Comment by jolestar** [comment]
https://github.com/rooch-network/rooch/blob/984aaa1ae40dff2072a90ad0ed5d8bc202c16805/crates/rooch-config/src/config.rs#L36-L42

We should ensure the parent dir exists or create_all for the parent.

**Comment by jolestar** [comment]
Use the `--skip-password` flag 

```bash
docker run --rm -v ~/tmp/rooch:/root ghcr.io/rooch-network/rooch:main init --skip-password
```

Or add `-it` to the docker flag to enable `/dev/tty`:

```bash
 docker run -it --rm -v ~/tmp/rooch:/root ghcr.io/rooch-network/rooch:main init
```
