### ISSUE TITLE
[Framework] TransactionAbstraction

### ISSUE THREAD

**Issue by jolestar** [rooch-network/rooch#14]
Decode the transaction in the Move code and provide an extension mechanism to the developers(Who want to embed MoveOS in their App).
Compatible with ETH transactions.

**Comment by baichuan3** [comment]
**Transaction lifecycle in Layer1**
<img width="782" alt="image" src="https://user-images.githubusercontent.com/1904567/236367920-939d7eb0-1e5a-42cd-8612-d5d2dc10a41f.png">

**Transaction Abstraction**
<img width="641" alt="image" src="https://user-images.githubusercontent.com/1904567/236367672-1355c0c8-0a17-4fc2-955d-e5f0e9352317.png">

**Transaction execute in VM**
<img width="1159" alt="image" src="https://user-images.githubusercontent.com/1904567/236366705-61c66791-38d9-4a30-8cfa-2957a9321cb3.png">
