### ISSUE TITLE
Unify `tx` and `txn`

### ISSUE THREAD

**Issue by jolestar** [rooch-network/rooch#141]
We sometimes use `tx` and sometimes use `txn` to abbreviate `transaction`. I think we should unify this. I suggest using `tx`, like `tx_hash`.

**Comment by templexxx** [comment]
isn't txn more commonly used? @jolestar

**Comment by jolestar** [comment]
Both usages are very common. For example, "tx" is used for BTC, ETH, and SUI, while "txn" is used for APTOS, EOS, and database fields. We should unify this. 

I prefer to use "tx" because it is more fluent when combined, such as 

"TxContext" vs "TxnContext"
"TxOutput" vs "TxnOutput"
"TxID" vs "TxnID"

...

**Comment by templexxx** [comment]
> Both usages are very common. For example, "tx" is used for BTC, ETH, and SUI, while "txn" is used for APTOS, EOS, and database fields. We should unify this.
> 
> I prefer to use "tx" because it is more fluent when combined, such as
> 
> "TxContext" vs "TxnContext" "TxOutput" vs "TxnOutput" "TxID" vs "TxnID"
> 
> ...

@jolestar 

Both of them is ok for me. Same issue I've talked with @steelgeek091 , we need to unify one

**Comment by baichuan3** [comment]
also, either is ok for me
