### ISSUE TITLE
[Bitcoin] Refactor process_utxos and add BitcoinSatStore to track inscriptions correctly

### ISSUE THREAD

**Issue by adshao** [rooch-network/rooch#1426]
According to the documentation on [inscriptions](https://docs.ordinals.com/inscriptions.html), inscriptions are inscribed on sats. This implies that in order to accurately track inscriptions with their correct sequence numbers to [ordinals.com](https://ordinals.com/), it is essential to monitor sats in alignment with the principles of [ordinal theory](https://docs.ordinals.com/overview.html).

Sats should be numbered and transferred according to the algorithm specified in [Ord BIP](https://github.com/ordinals/ord/blob/master/bip.mediawiki).

The relationship between sats and inscriptions is summarized as follows:
* Multiple inscriptions can be inscribed on the same sat by [reinscription](https://docs.ordinals.com/inscriptions.html#reinscriptions)
* Multiple inscriptions can be inscribed on different sats in an input by [pointer](https://docs.ordinals.com/inscriptions/pointer.html)
* An inscription is only transferred when its corresponding sat is sent to a new owner
* Cursed inscription should be uncursed after [the jubilee height](https://github.com/ordinals/ord/pull/2656)

Our current tracking of inscriptions seems to be incorrect in the following aspects:
* coinbase tx should be processed in the end of the block, as seen in [rooch](https://github.com/rooch-network/rooch/blob/406e1a60458e2f1b83e0659d0195adf7b54e3062/frameworks/bitcoin-move/sources/light_client.move#L235) and [ord](https://github.com/ordinals/ord/blob/c5e63e4dd2562bc6aedb6b17c6821dbe58fa3ff6/src/index/updater.rs#L547)
* The transfer of an inscription is identified by tracking the old sats and inscriptions associated with the input, as detailed in [ord](https://github.com/ordinals/ord/blob/c5e63e4dd2562bc6aedb6b17c6821dbe58fa3ff6/src/index/updater/inscription_updater.rs#L98)

**Comment by adshao** [comment]
In fact, tracking `SAT_TO_SATPOINT` and `OUTPOINT_TO_SAT_RANGES` within [index_sats](https://github.com/ordinals/ord/blob/c5e63e4dd2562bc6aedb6b17c6821dbe58fa3ff6/src/index/updater.rs#L449) is not necessary. Instead, our focus should solely be on monitoring `satpoint_to_sequence_number` and `sequence_number_to_inscription_entry` as demonstrated in [inscriptions_on_output](https://github.com/ordinals/ord/blob/c5e63e4dd2562bc6aedb6b17c6821dbe58fa3ff6/src/index.rs#L1954).

**Comment by jolestar** [comment]
Implement the full inscription logic at https://github.com/rooch-network/rooch/blob/main/frameworks/bitcoin-move/sources/inscription_updater.move

And verify the case with ord events in https://github.com/rooch-network/rooch/blob/main/crates/rooch-framework-tests/src/tests/bitcoin_tester_test.rs

Except:
1. Sat index: Rooch does not handle the Sat index.
2. Fee: the fee in the ordinals protocol is to display the cost; Rooch does not handle the fee logic.
