### ISSUE TITLE
[Bitcoin] Improve the performance of Rooch importing BTC full node data

### ISSUE THREAD

**Issue by baichuan3** [rooch-network/rooch#1432]
Rooch currently imports BTC full node data performance data, which is about 1,000 blocks per day.

After Relayer optimization:
1. Make the output returned by the RPC to option (not returned by default)
2. Transform Bitcoin Client into Actor mode
3. Use the Release version of Rooch cli

Import performance increased to 3000 blocks per day.

Goal
Import performance improved to 10,000 blocks per day.

**Comment by baichuan3** [comment]
Import BTC block data and some optimizations have been made to the Indexer.

1. Split Indexer single SQLite into multiple files (database) by table
2. Set the switch to stop writing Transactions + State Sync data when importing data.

Now it can import 6,000 to 7,000 blocks every day, which is about 1.5 times higher than before.

**Comment by jolestar** [comment]
The first stage is complete, and later optimizations are tracked with a new issue.
