### ISSUE TITLE
[test] Figure out why rooch-framework-tests is so slow

### ISSUE THREAD

**Issue by jolestar** [rooch-network/rooch#1443]
```
cargo nextest run -p rooch-framework-tests -p rooch-integration-test-runner -v -j 1
```

<img width="1207" alt="Screen Shot 2024-03-14 at 09 30 39" src="https://github.com/rooch-network/rooch/assets/77268/f6c753a6-4c41-435d-b933-b4f26eb90f14">

**Comment by jolestar** [comment]
> It seems normal with command `cargo test -p rooch-framework-tests -p rooch-integration-test-runner -j 1`, maybe we can use `cargo test` to do these tests.

Help to update the GitHub action file. 

cc @shelmesky

**Comment by steelgeek091** [comment]
> > It seems normal with command `cargo test -p rooch-framework-tests -p rooch-integration-test-runner -j 1`, maybe we can use `cargo test` to do these tests.
> 
> Help to update the GitHub action file.
> 
> cc @steelgeek091

OK.

**Comment by jolestar** [comment]
I think the reason is that the nextest does not share the static variable between tests, so it needs to rebuild Genesis for every test. 

https://nexte.st/book/how-it-works.html
