### ISSUE TITLE
[Framework]  upgrade mechanism including compatibility check 

### ISSUE THREAD

**Issue by baichuan3** [rooch-network/rooch#146]
There are several upgrade modes:

1) To upgrade already published Move code, simply attempt to republish the code at the same address that it was previously published, like Aptos, [https://aptos.dev/move/book/package-upgrades/](url)
2) The first deployment is separate from upgrade, and a separate update command line is provided to upgrade the contract, like Sui,  [https://docs.sui.io/build/package-upgrades](url)

After supporting a module initialization method, https://github.com/rooch-network/rooch/issues/63, need to ensure the init function only calls on the first deployment. since the Move runtime does not  know about new packages created, the first deployment contract and the upgrade contract need to be handled separately. 

So option 2 looks like a more suitable choice, but more complicated.

**Comment by jolestar** [comment]
compatibility check is finished and Upgrade policies is traced via #705
