### ISSUE TITLE
Determine the parameter types supported by the "entry fun"

### ISSUE THREAD

**Issue by wubuku** [rooch-network/rooch#148]
When we use Sui CLI to compile Move contracts, it will prompt for unsupported parameter types that appear in the "entry fun".

For example, this "fun":

```Move
    public entry fun test(_a: Option<vector<Day>>){}
```

When executing:

```shell
sui move build
```

The error prompt will look like this:

```shell
Error executing ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: SuiMoveVerificationError, source: Some("Invalid entry point parameter type. Expected primitive or object type. Got: 0x1::option::Option<vector<0x0::day::Day>>"), command: None } }
```

If we use Aptos CLI instead, there won't be such a prompt. Currently, Rooch also works in the same way.

Also, Sui supports a variety of parameter types. For example, this "fun" is also acceptable:

```Move
    public entry fun test(
        _b:vector<Option<u64>>,
        _c:Option<vector<u64>>,
    ){}
```

To some extent, support for Option may not be necessary. We can consider using a vector instead and let the entry fun implement a vector_to_option conversion logic to handle it. It could be done like this:

```Move
    fun vector_to_option<V : drop>(v: vector<V>): Option<V> {
        if (vector::length(&v) == 0) { option::none() } else {
            option::some(
                vector::pop_back(&mut v)
            )
        }
    }
```

So far, my expectations for the parameter types that Rooch can support in entry funs are  at least as follows :

```Move
// Primitive types:
// ...
String,
ObjectID,
// vector:
vector<u8>,
vector<u64>,
vector<u128>,
// ...
vector<String>,
vector<ObjectID>,
//
// Does anyone else have anything to add? Please comment.
// 
```

By the way, Sui CLI supports "complex" parameters by using JSON. For example:

```shell
sui client call --package _PACKAGE_ID_ --module day_summary_aggregate --function create \
--args \"string_arg\" true  \"vector_u8_meta_data\" '["string_array_data_item_1", "string_array_data_item_2"]' '["vector_u8_optional_data"]' \"_OBJECT_ID_\" \
--gas-budget 100000
```

For parameters of type `vector<u8>`, you can pass in a string.

@baichuan3

**Comment by jolestar** [comment]
We need a verifier #152
