### ISSUE TITLE
[Store]proposal: separate rocksdb configs of moveos and rooch

### ISSUE THREAD

**Issue by popcnt1** [rooch-network/rooch#1593]
now we reuse StoreConfig passed to Rooch for MoveOS DB, actually they have different workload, we should use two kinds of configs(in rooch_rpc_server::init_storage for init moveos db and rooch db)

1. share the same rocksbconfig struct between moveos and rooch db
2. their  arguments could be passed to rooch rpc service separately

**Comment by jolestar** [comment]
Merge moveos store and rooch store to one rocksdb instance.
