### ISSUE TITLE
Ignore link check to https://tokei.rs/b1/github/rooch-network/rooch

### ISSUE THREAD

**Issue by jolestar** [rooch-network/rooch#1614]
https://github.com/rooch-network/rooch/actions/runs/8818194035/job/24206415911?pr=1600

```
* [525] [https://tokei.rs/b1/github/rooch-network/rooch?category=lines](https://tokei.rs/b1/github/rooch-network/rooch?category=lines) | Failed: Network error: Unknown status code
```

**Comment by geometryolife** [comment]
这个问题我感觉有些奇怪，因为原来已经忽略过 https://tokei.rs/b1/github/rooch-network/rooch?category=lines 这个链接了，但是我尝试升级了 lychee-action 到最新版本，仍然会出现这个错误。

现在我发现这个图片的服务器无法提供服务了，仓库 README 也没有正常显示出来，现在有一个临时解决方案是注释掉

![image](https://github.com/rooch-network/rooch/assets/54882546/4f56b0a0-fca5-450f-b1f1-df70f3aa6a1f)

**Comment by jolestar** [comment]
可以先注释掉。
