### ISSUE TITLE
[bug] SessionKey can create SessionKey

### ISSUE THREAD

**Issue by jolestar** [rooch-network/rooch#1625]
https://github.com/rooch-network/rooch/blob/417f226614f56caa4e8657a067d9bf952567530f/frameworks/rooch-framework/sources/session_key.move#L116-L117

The assert ensures users can not use a SessionKey to create a new SessionKey, but it does not work. 

## Reason

https://github.com/rooch-network/rooch/blob/417f226614f56caa4e8657a067d9bf952567530f/crates/rooch-types/src/framework/auth_validator.rs#L152-L164

the `transaction_validtor` of above should `transaction_validator`.

1. All the logic with `TxValidateResult` should be checked.
2. Write a test to ensure the assert.

**Comment by feliciss** [comment]
Since I've handled session keys before, I will possibly look at this issue.

**Comment by feliciss** [comment]
Is there a step on how to reproduce the bug described above? @jolestar

**Comment by jolestar** [comment]
1. Create a SessionKey via cli.
2. Use the SessionKey to create another SessionKey.

**Comment by feliciss** [comment]
> the transaction_validtor of above should transaction_validator.

Did you mean the `transaction_validtor` of above should be replaced to `auth_validator`?

**Comment by jolestar** [comment]
`transaction_validtor` is a typo.

**Comment by feliciss** [comment]
> `transaction_validtor` is a typo.

I tried to change `transaction_validator` to `auth_validator`. Before this change, the output was:

```zsh
---- tests::transaction_validator_tests::test_session_key_from_session_key_failure_rooch stdout ----
[debug] 0x1::option::Option<u64> {
  vec: []
}
[debug] 0x1::option::Option<vector<u8>> {
  vec: []
}
```

After this change, I noticed there was a `0` by the u64 `auth_validator_id` but the `session_key` was still empty.

I doubt if this's related to `builtin_validators::genesis_init` after the change, cause there seems no way to put `session_key` into `auth_validator`.

**Comment by jolestar** [comment]
Push the `test_session_key_from_session_key_failure_rooch` to #1657, and I will help to figure it out.

**Comment by feliciss** [comment]
> @feliciss Push the `test_session_key_from_session_key_failure_rooch` to #1657, and I will help to figure it out.

Got it.
