### ISSUE TITLE
[RPC] RPC API design

### ISSUE THREAD

**Issue by jolestar** [rooch-network/rooch#165]
Currently, there are two styles of RPC naming in the system:

1. Direct method names such as `submit_txn`, `view`, `resource`.
2. Prefixed names such as `accounts.get`, `accounts.balance`.

It is important to unify these naming styles. However, adding a prefix to each API, such as `transaction.get` or `state.get`, would create additional complexity for the developer.

Therefore, I suggest the following solution:

1. All necessary public API in Rooch should be unified under the prefix "rooch". For example, `rooch.submit_txn` and `rooch.view`.
2. Additionally, API requiring special permission rules should use independent prefixes such as `accounts`, `debug`, or `system`.

### Ref:
1. Discussion: https://discord.com/channels/1078938449974935592/1110388019233558558
2. #12 
3. #41

**Comment by baichuan3** [comment]
Sui's RPC API interface has a uniform prefix of `sui_`, such as sui_transferObject. In my opinion, `rooch.`is similar to `sui_` prefix, and all interfaces should have an independent non `rooch.` prefix, such as accounts, state, tx (or transaction), which will better indicate the purpose of the interface, and also for developers more friendly.

**Comment by jolestar** [comment]
Three styles of RPC API:

1. ETH and Sui style:  `eth_sendTransaction`, `eth_getTransactionByHash`, `sui_getTransactionBlock`, `sui_executeTransactionBlock`, `sui_dryRunTransactionBlock`.
2. Aptos REST style: `/v1/transactions`,`/v1/blocks`, `/v1/events` GET|POST.
3. Starcoin style: `chain.get_transaction`, `chain.get_events`, `txpool.submit_transaction`, `contract.dry_run"`.

**Comment by jolestar** [comment]
I prefer to use ETH and Sui style:

1. Avoid using too many namespaces, which can lead to overthinking to place API under which namespace. Developers may also need help remembering the API namespaces.
2. It will be convenient to map between Rooch RPC and ETH RPC later when designing the ETH RPC Proxy.

So I suggest we provide three namespaces:

1. `rooch_`: All public RPC API about the rooch container like `eth_` or `sui_`
2. `wallet_`: A local wallet in the Rooch node. Default open to local request. I think the `wallet_` is more suitable than the `account_`.
3. `node_manager_`: All API to manage the local node, include the `debug_` in ETH. Default open to local request.
4. `index_`: For the index API, the user can disable the Index Service and API.
