### ISSUE TITLE
cargo build on windows  rooch

### ISSUE THREAD

**Issue by jamesatomc** [rooch-network/rooch#1667]
<img width="1284" alt="Screenshot 2024-05-12 150805" src="https://github.com/rooch-network/rooch/assets/56755216/1c0e8783-d516-4e01-8930-aa387be7eacd">

  = note: LINK : fatal error LNK1181: cannot open input file 'sqlite3.lib'

**Comment by jolestar** [comment]
```
Error:    --> frameworks\moveos-stdlib\src\natives\moveos_stdlib\wasm.rs:465:58
    |
465 |                         dyn Fn(libc::c_int, *const libc::siginfo_t, *const libc::c_void) -> bool
    |                                                          ^^^^^^^^^ not found in `libc`
```

**Comment by jamesatomc** [comment]
I also encountered this error.
