### ISSUE TITLE
[bitcoin-move] Handle reorg

### ISSUE THREAD

**Issue by jolestar** [rooch-network/rooch#1685]
https://github.com/rooch-network/rooch/blob/3abd787b9b4d0870b53d71ca88295d4d761b3d89/frameworks/bitcoin-move/sources/bitcoin.move#L81-L83

**Comment by feliciss** [comment]
Will handle this issue together with #1622.

**Comment by jolestar** [comment]
@feliciss Handle #1622 first.

**Comment by feliciss** [comment]
> @feliciss Handle #1622 first.

Got it. I had a draft PR:  #1705. Please review it first and I will look at #1622 at the time.
