### ISSUE TITLE
[Crypto] implement proc_macro_derive for CryptoHash and CryptoHasher

### ISSUE THREAD

**Issue by baichuan3** [rooch-network/rooch#169]
implement crypto library, 
like https://github.com/aptos-labs/aptos-core/blob/main/crates/aptos-crypto-derive/src/hasher.rs in Aptos
or https://github.com/starcoinorg/starcoin-crypto/blob/main/crypto/crypto-macro/src/lib.rs in Starcoin

maybe base on unify crypto crate depend on https://github.com/rooch-network/rooch/issues/151

**Comment by jolestar** [comment]
We just use the `h256::sha3_256_of(bcs::to_bytes(&T))` to get the Hash. 

The `CryptoHash` macro_derive adds salt to the hash result, more secure but hard to keep consistent in other systems.

For example, SDKs in non-Rust programming languages and smart contract language(Move or Solidity).

**Comment by jolestar** [comment]
This issue is also related to #151.

**Comment by jolestar** [comment]
We do not plan to introduce the salt hash solution. https://discord.com/channels/1078938449974935592/1110583064830165062

We need a trait for auto implementing the hash function and unifying the hash function name.
