### ISSUE TITLE
[Bitcoin] Execute Bitcoin blocks by transaction

### ISSUE THREAD

**Issue by jolestar** [rooch-network/rooch#1797]
## Motivation

Currently, we execute the entire block of Bitcoin as one transaction, which has several problems:

1. If a block contains a large number of transactions, executing each one will take a long time, affecting the user experience.
2. This way, transactions in the block cannot be executed in parallel.

So, we need to split the block into transactions and execute blocks by transaction.

## Solution

TODO

**Comment by feliciss** [comment]
Does this issue have a deadline for PR #1705?

**Comment by jolestar** [comment]
> Does this issue have a deadline for PR #1705?

This issue also needs to include the Reorg solution.
