### ISSUE TITLE
[CLI] Refactor the CLI result

### ISSUE THREAD

**Issue by jolestar** [rooch-network/rooch#1803]
Refactor the CLI result support output json to every command.

Currently, we support output json in some commands, such as `account list`. But we sometimes need to parse the command output, such as in the integration test(`cmd.feature`).

- [x] #1895

**Comment by feliciss** [comment]
May I handle this issue?

**Comment by jolestar** [comment]
This is finished by adding the `execute_serialized` function to the CommandAction. 

https://github.com/rooch-network/rooch/blob/2910febd4b9b6717e229a0bfe9b46e8bbe746b54/crates/rooch/src/cli_types.rs#L28-L40

If you have a better solution, you can promote a refactor suggestion. @feliciss
