### ISSUE TITLE
Error when serialize and deserialize FileBasedKeystore

### ISSUE THREAD

**Issue by pause125** [rooch-network/rooch#184]
I was trying to write test for FileBasedKeystore's [serialize and deserialize](https://github.com/rooch-network/rooch/blob/c9586924cf9ddc52532aae001f09e8389a45208f/crates/rooch-key/src/keystore.rs#LL97C9-L97C9), but found the implementation just serialize and deserialize the FileBasedKeystore.path field with FileBasedKeystore.keys ignored.

Is this designed or just missing the implementation for FileBasedKeystore.keys?

**Comment by jolestar** [comment]
It could be for security and not auto-serialize the keys. @wow-sven

**Comment by pause125** [comment]
> It could be for security and not auto-serialize the keys. @wow-sven

If not serialize the keys and restructure them from the path when deserialize, the serialization and deserialization for FileBasedKeystore will be fallible as the path is variable. And we shoud make sure the serialization string should not be transfered to other environments as the path may not exist of with wrong value in other enviroments.

**Comment by jolestar** [comment]
I think we should not transfer the FileBasedKeystore

**Comment by wow-sven** [comment]
> I think we should not transfer the FileBasedKeystore

yes,

**Comment by wow-sven** [comment]
> > It could be for security and not auto-serialize the keys. @wow-sven
> 
> If not serialize the keys and restructure them from the path when deserialize, the serialization and deserialization for FileBasedKeystore will be fallible as the path is variable.
> 
> We shoud make sure the serialization string should not be transfered to other environments as the path may not exist of with wrong value in other enviroments.



> > It could be for security and not auto-serialize the keys. @wow-sven
> 
> If not serialize the keys and restructure them from the path when deserialize, the serialization and deserialization for FileBasedKeystore will be fallible as the path is variable.
> 
> We shoud make sure the serialization string should not be transfered to other environments as the path may not exist of with wrong value in other enviroments.

we only need to recover  from the path, and the path can be modified by the user, but it is not currently exposed by the CLI.

**Comment by wow-sven** [comment]
> It could be for security and not auto-serialize the keys. @wow-sven

yes

**Comment by jolestar** [comment]
Is this issue resolved?
