### ISSUE TITLE
[rpc] Change the default port

### ISSUE THREAD

**Issue by jolestar** [rooch-network/rooch#1840]
The default RPC port is 50051; it is the gRPC default port. We can change the default port to avoid port conflict.

**Comment by v1xingyue** [comment]
So we should choose one luck number for rooch. 😄

**Comment by jolestar** [comment]
6767,15002,9333

**Comment by jolestar** [comment]
6767: UPnP
9333: Bitcoin & Litecoin
15002: Remote Desktop Protocol
