### ISSUE TITLE
[std] Introduce TypeTable 

### ISSUE THREAD

**Issue by jolestar** [rooch-network/rooch#19]
TypeTable can represent the account resource table, and this is part of StorageAbstraction

ref: https://github.com/move-language/move/issues/140

```
mos_std::type_table {
   struct TypeTable{
      inner: Table<String,Any>()
   }

   /// Create a new TypeTable.
   public fun new(): TypeTable {
        TypeTable {
            inner: table::new<String, Any>(),
        }
   }

   public fun add<V>(table: &mut TypeTable, val: V) {
        let key = type_info::type_name<V>();
        table::add(&mut table.inner, key, any::new(val))
   }
}
```

## Dependency

* Any #18

**Comment by jolestar** [comment]
> There may be a limitation: if we want to store type `V` in a `TypeTable` through `Any` type, the type `V` must have the `copy` or `drop` attribute, which nevertheless is not set for most resource types.

How about we remove the `drop` ability from Any? another problem is if a type only has the `key` ability, it also can not store in Any.

Maybe we use `vector<u8>` to store the value's binary? and directly use the `bcd:from_bytes<V>` to decode the value.

```
struct TypeTable{
    inner: Table<String,vector<u8>>()
}
```

**Comment by pause125** [comment]
1. We can't remove the `drop` ability from `Any` unless we change `bcs::to_bytes<MoveValue>(v: &MoveValue)`  to `bcs::to_bytes<MoveValue>(v: MoveValue)`.
2. Using `vector<u8>` as value of `TypeTable` will break the type's security, it will make all types copyable even if the type has no `copy` ability.

**Comment by jolestar** [comment]
It was a difficult decision, and I made this feature TBD.

**Comment by jolestar** [comment]
We implement the TypeTable with RawTable, and this feature also requires the #64 .
