### ISSUE TITLE
[portal] Set the default max_gas_amount to 50000000

### ISSUE THREAD

**Issue by jolestar** [rooch-network/rooch#1903]
max_gas_amount 当前默认值是 5000000，这个值太小了，可以设置成 50000000

<img width="840" alt="Screenshot 2024-06-17 at 22 02 07" src="https://github.com/rooch-network/rooch/assets/77268/bd85410a-142e-4d8f-bf15-427c0fb41c32">

另外如果 status 不是 `executed`, 需要显示成红色，表示失败。

**Comment by TwilightLogic** [comment]
I will increase it a little bit. What is max?🧐

**Comment by TwilightLogic** [comment]
Ok I'll increase it to '5000000'
