### ISSUE TITLE
Secure special handling of the from_bytes<T> function.

### ISSUE THREAD

**Issue by steelgeek091** [rooch-network/rooch#210]
In the file `moveos/moveos-stdlib/moveos-stdlib/sources/bcd.move`, the following tasks need to be completed:

1. For the from_bytes function, it needs to be handled specially in the verifier to implement the same functionality as `#[private_generics]` without requiring annotations.
2. The fields contained in `T` are either primitive types or are defined by the module that calls from_bytes. 
3. Make the native function `from_bytes` private and without annotations.
4. Provide a public function and add `private_generics`, perhaps named `public_from_bytes` or `generic_from_bytes`.
5. The `to_xx` function should call the private from_bytes.

**Comment by jolestar** [comment]
relative issue #145

**Comment by jolestar** [comment]
repeat with #145. Close this one.
