### ISSUE TITLE
[Metrics] Raw store Metrics

### ISSUE THREAD

**Issue by baichuan3** [rooch-network/rooch#2139]
### Rawstore Metrics

- raw_store_iter_latency_seconds
- raw_store_iter_bytes
- raw_store_get_latency_seconds
- raw_store_get_bytes
- raw_store_multiget_latency_seconds
- raw_store_multiget_bytes
- raw_store_put_latency_seconds
- raw_store_put_bytes
- raw_store_write_batch_latency_seconds
- raw_store_write_batch_bytes
- raw_store_put_sync_latency_seconds
- raw_store_put_sync_bytes
- raw_store_write_batch_sync_latency_seconds
- raw_store_write_batch_sync_bytes
- raw_store_delete_latency_seconds

**Comment by popcnt1** [comment]
#2136
