### ISSUE TITLE
Parameter types that need support for "entry fun"

### ISSUE THREAD

**Issue by wubuku** [rooch-network/rooch#215]
Based on the requirements of some application examples currently being tested, I believe it is necessary to have the following list of parameter types supported in the "entry fun":

```
// Primitive types:
bool,
u8,
u16,
// ...
String,
ObjectID,
// vector:
vector<u8>,
vector<u64>,
vector<u128>,
// ...
vector<String>,
vector<ObjectID>,
// ...
// Does anyone else have anything to add? Please comment.
```

**Comment by jolestar** [comment]
relative #202

**Comment by steelgeek091** [comment]
resolved in PR https://github.com/rooch-network/rooch/pull/196
