### ISSUE TITLE
[CLI] Support for passing different types of parameters to entry fun

### ISSUE THREAD

**Issue by wubuku** [rooch-network/rooch#217]
The types of parameters I expect to be supported are here: #215

For primitive types, it seems that the current CLI can pass parameters like this:

```shell
--args @0xae43e34e51db9c833ab50dd9aa8b27106519e5bbfd533737306e7b69ef253647
--args 1u8
```

But we want entry fun to support some complex types, and we don't know how to pass in parameters via the CLI yet.

The method of sui is to directly support JSON in the cli, like:

```shell
sui client call --package _PACKAGE_ID_ --module day_summary_aggregate --function create \
--args u16_year_number \"string_calendar\" u8_month_is_leap u8_day_number \"string_day_time_zone\" \"string_description\" \"vector_u8_meta_data\" '["string_array_data_item1", "string_array_data_item2"]' '["vector_u8_optional_data"]' \"_DAY_SUMMARY_DAY_SUMMARY_ID_TABLE_OBJECT_ID_\" \
--gas-budget 100000
```

Also, I would like the entry fun's vector<u8> type argument to be passed in a string; but conversely, the String type argument is not allowed to be passed in a u8 vector, which I think is acceptable.

**Comment by wubuku** [comment]
I wonder how to pass CLI parameters for an entry fun like the following?

```Move
    public entry fun add_foo_table_item(
        storage_ctx: &mut StorageContext,
        object_id: ObjectID,
        key: String,
        val: String,
    ) {
        let obj = something::remove_something(storage_ctx, object_id);
        let update_obj = something_do_logic::add_foo_table_item(storage_ctx, obj, key, val);
        something::add_something(storage_ctx, update_obj);
    }
```

Also, maybe the types of arguments listed in #215 that require CLI support to be passed in are still necessary in the v0.1 milestone. Otherwise, after v0.1 comes out, it seems harder to write/test a more realistic looking application using the new object model.

**Comment by wubuku** [comment]
> Otherwise, after v0.1 comes out, it seems harder to write/test a more realistic looking application using the new object model.

For example, if we use a Table to store multiple `OrderItem`s belonging to an `Order`, it is quite common to manipulate several OrderItems at the same time, for example, if I want to implement the "XX% discount on N items" function, we may provide multiple OrderItem IDs in the transaction. This ID may be an ObjectID (for example, using the Product ID as the ID of the OrderItem), so it is necessary to pass in `vector<ObjectID>` from the client.

Of course, passing in a `vector<u8>` parameter and deserializing it to a `vector<ObjectID>` is a way to "get around" this problem, but it's a bit tricky.

@pause125 @baichuan3

**Comment by baichuan3** [comment]
https://docs.sui.io/build/sui-json

**Comment by pause125** [comment]
I will work on this. I am going using the Aptos-style CLI types.
