### ISSUE TITLE
[portal] Add Public View Function

### ISSUE THREAD

**Issue by Mine77** [rooch-network/rooch#2187]
We need a public view function for the users to view another account's asset and transaction information in the Portal.
My idea is to rewrite the bottom block in the side bar for this function:
<img width="276" alt="image" src="https://github.com/user-attachments/assets/a51c01fb-52c9-46fe-848d-36e968e745b5">

It should be a search bar where users can put in a Bitcoin address, and jump to the public view page of that address.
A basic user story:
- User enter the address in the search bar and click a jump button
  - if the address has an according Rooch account then jump to the account's "View Page"
  - if not then return error
- The view page should has an URL in this structure: https://portal.rooch.network/view/[bitcoin address]
- The view page should have the same UI as the portal but with only Assets, Transactions and Settings page available
- In these pages, the information of the viewed account should be fetched and displayed
- When in the view page, the search bar should turn into a displaying area that shows the address that is being viewed, with a status icon showing that it is the public view function that is ongoing, and a button for jumping to the original account should be provided

**Comment by jolestar** [comment]
We also need the view page for Inscription and UTXO, the same as

https://ordinals.com/inscription/43a9d0a1ecd3282ffec820d0b01a2f839021001f215f1736eab933aa3c1ca2c4i1

https://portal.rooch.network/view/inscription/$InscriptionID
