### ISSUE TITLE
[ts-sdk-kit]: no RoochClientProvider export

### ISSUE THREAD

**Issue by birchwork** [rooch-network/rooch#2191]
in `clientProvider.ts`, RoochClientProvider is exported, but it is not exported in `provider/index.ts`. Should we export RoochClientProvider in `provider/index.ts`?

**Comment by wow-sven** [comment]
We don't need to export clientProvider.ts, rooch provider will contain clientProvider

**Comment by birchwork** [comment]
[here](https://github.com/rooch-network/rooch/blob/e2ee494f8de7b814dc04d08d8059ece916330e23/infra/dashboard/src/pages/_app.tsx#L112-L113), where i get a little confused

**Comment by wow-sven** [comment]
> [here](https://github.com/rooch-network/rooch/blob/e2ee494f8de7b814dc04d08d8059ece916330e23/infra/dashboard/src/pages/_app.tsx#L112-L113), where i get a little confused

@tanstack/react-query

**Comment by jolestar** [comment]
I close this issue, feel free to reopen it if necessary.
