### ISSUE TITLE
[frontend] Transactions cannot be displayed completely if there are too many transaction pages

### ISSUE THREAD

**Issue by pause125** [rooch-network/rooch#2248]
See the following screenshot:

![image](https://github.com/user-attachments/assets/0a8b3bae-daa4-466f-b891-43bda4c1271b)

**Comment by wow-sven** [comment]
1. Previous button should be fixed, if too many page numbers can be used... omit the middle.
2. The number of single page displays can be modified

**Comment by nlyrthiia** [comment]
https://github.com/rooch-network/rooch/pull/2309

See if this PR can help you solve your problem

**Comment by nlyrthiia** [comment]
done.
