### ISSUE TITLE
When the execution of the contract is failed, the error message shows the specific function name

### ISSUE THREAD

**Issue by baichuan3** [rooch-network/rooch#227]
The current error message shows function number, not sure whether it is in the natural order of moduleli or in the dictionary order?

```
"ExecutionFailure": {
      "location": {
        "Module": {
          "address": "0000000000000000000000000000000000000000000000000000000000000001",
          "name": "raw_table"
        }
      },
      "function": 9,
      "code_offset": 0
    }
  }
}
```

Expect to display the error function name directly.

**Comment by steelgeek091** [comment]
@baichuan3 Which part of the code triggers the return of these error messages?

**Comment by baichuan3** [comment]
> @baichuan3 Which part of the code triggers the return of these error messages?

This error will be thrown when the rooch move run is executed on the command line and the execution contract method fails.

corresponding to the specific code location
https://github.com/rooch-network/rooch/blob/adce7f294e3bcc6f0374f23acb11e02ce712e661/moveos/moveos/src/moveos.rs#L240-L276

**Comment by steelgeek091** [comment]
Alright, received.

**Comment by steelgeek091** [comment]
@baichuan3 Can we take a look at the related error messages? This code block is too long, and it's not easy to find where the error occurred.

**Comment by jolestar** [comment]
There are usually two types of errors in Move:

1. ExecutionFailure: A native method throws an error, or an instruction throws an error.
2. Abort: The contract explicitly aborts or aborts through assert.

Designing these two scenarios can reproduce the errors.

Starcoin's implemention:

https://github.com/starcoinorg/starcoin/blob/ee3c02fc55cdf99a0d00072d1f2847052641ca73/vm/vm-status-translator/src/lib.rs#L80
