### ISSUE TITLE
[system] Should we put the full AccumulatorInfo to TransactionSequeceInfo

### ISSUE THREAD

**Issue by jolestar** [rooch-network/rooch#2289]
Should we put the full AccumulatorInfo to TransactionSequeceInfo?
The Accumulator tree can not be built from one root.

cc @popcnt1 @baichuan3

**Comment by baichuan3** [comment]
AccumulatorInfo is only needed when repairing data. This field is not used in normal scenarios. There may be two ways to deal with it:

1. If we only consider revealing the latest transaction, store both current AccumulatorInfo and previous AccumulatorInfo in SequencerInfo, like this

```
pub struct SequencerInfo {
    pub last_order: u64,
    pub last_accumulator_info: AccumulatorInfo,
    pub previous_accumulator_info: AccumulatorInfo,
}
```

2. If we want to support revealing any transaction, consider maintaining the tx_order -> AccumulatorInfo mapping
