### ISSUE TITLE
[Framework] Native function support deriving multi-sign address 

### ISSUE THREAD

**Issue by jolestar** [rooch-network/rooch#2295]
```move 
rooch_framework::bitcoin_address{
  public native fun verify_bitcoin_address_with_public_key(addr: &BitcoinAddress, pk: &vector<u8>): bool;
  public native fun derive_taproot_multisign_public_key(public_keys: &vector<vector<u8>>, threshold: u64): vector<u8>;
    public native fun derive_taproot_address(taproot_public_key: &vector<u8>): BitcoinAddress;
}
```

#2294

**Comment by feliciss** [comment]
>   public native fun verify_bitcoin_address_with_public_key(addr: &BitcoinAddress, pk: &vector<u8>): bool;

Secp256k1 public key can be converted to bitcoin p2tr and p2pkh. Should it be handled for all cases or just p2tr and p2pkh addresses from the public key bytes?

**Comment by feliciss** [comment]
> > ```move
> >   public native fun verify_bitcoin_address_with_public_key(addr: &BitcoinAddress, pk: &vector<u8>): bool;
> > ```
> 
> Secp256k1 public key can be converted to bitcoin p2tr and p2pkh. Should it be handled for all cases or just p2tr and p2pkh addresses from the public key bytes?

To verify it, convert the pk bytes to the bitcoin address (address type unknown at the time) and check if it's the same address with the first `address` param.

**Comment by jolestar** [comment]
The native function definition is changed. #2294

**Comment by feliciss** [comment]
> The native function definition is changed. #2294

I will change it to `derive_taproot_multisig_public_key` instead of `multisign` as I will use multisig2 rust lib to achieve this feature.
