### ISSUE TITLE
[CLI] Support query object fields

### ISSUE THREAD

**Issue by jolestar** [rooch-network/rooch#2317]
Add to the `rooch object` command or add a `rooch dynamic-field` command.

*  Call `getFieldStates` for a special dynamic field with a key.
*  Call `listFieldStates` to list the dynamic fields of an Object.

**Comment by feliciss** [comment]
Is this issue available for resolving?

**Comment by jolestar** [comment]
> Is this issue available for resolving?

You can handle this
