### ISSUE TITLE
[RPC]Add an API or API argument option to query an object based on the specific root state.

### ISSUE THREAD

**Issue by steelgeek091** [rooch-network/rooch#2330]
Currently, objects are queried based on the latest root state. An interface is needed to query objects based on a specific root state.

**Comment by jolestar** [comment]
1. Add `state_root: Option<H256>` to `StateOptions`.
2. Query state with the special state_root:
https://github.com/rooch-network/rooch/blob/69e03e7680216d2995ddf45864215e745370c5d6/crates/rooch-executor/src/actor/reader_executor.rs#L166-L176
3. Implement StateReslver to Client

**Comment by jolestar** [comment]
Finished in #2616
