### ISSUE TITLE
[framework] Auto bind bitcoin address to rooch address when transfer

### ISSUE THREAD

**Issue by jolestar** [rooch-network/rooch#2340]
Auto bind bitcoin address to rooch address when transferring coin or object.

https://github.com/rooch-network/rooch/blob/d057118b6f1139ac0225a00be11644897340f4a6/frameworks/rooch-framework/sources/transfer.move#L28-L36

https://github.com/rooch-network/rooch/blob/d057118b6f1139ac0225a00be11644897340f4a6/frameworks/rooch-framework/sources/transfer.move#L59-L66

**Comment by feliciss** [comment]
Is this issue available for resolving?
