### ISSUE TITLE
[ts-sdk-kit]: useWallets return error

### ISSUE THREAD

**Issue by lybenson** [rooch-network/rooch#2356]
There is no unisat wallet installed in chrome. However, it returns the UnisatWallet object when using useWallets()

```ts
 const wallets = useWallets()
 // wallets: [UniSatWallet] 
```

**Comment by nlyrthiia** [comment]
In fact, you can interpret useWallets as wallets supported by rooch, and it's up to you to determine whether the user has installed the wallet in the browser or not. For a concrete example, you can see my template: https://github.com/nlyrthiia/Rooch-Dapp-Template

**Comment by nlyrthiia** [comment]
In some dapps, it is necessary to list all supported wallets. Instead of showing only the wallets installed by the browser. So this is not an ERROR.
