### ISSUE TITLE
[CLI]Need rooch sign and validator command

### ISSUE THREAD

**Issue by v1xingyue** [rooch-network/rooch#2381]
Rooch cli tools need sign and validator command. 

- sign       use account secret key to sign content hex bytes 
- validator  validator the signature by the rooch account signer.

**Comment by feliciss** [comment]
Is this issue available for handling?

**Comment by jolestar** [comment]
> Is this issue available for handling?

@v1xingyue handle this

**Comment by v1xingyue** [comment]
Okay I'll handle this

**Comment by jolestar** [comment]
1. The `rooch account sign` command should add a prefix to the message, 

`Bitcoin Signed Message:\n`

https://github.com/rooch-network/rooch/blob/46dedc44f88f31994ec3ec41f2fc039357e8a01b/frameworks/rooch-framework/sources/auth_validator/auth_payload.move#L11-L12

We can wrap it into a struct, like `AuthPayload`, and we need to ensure the signed result is the same as the Bitcoin wallet result.

2. Provide a verify command, and verify message move function.

**Comment by feliciss** [comment]
> 1. The `rooch account sign` command should add a prefix to the message,
> 
> `Bitcoin Signed Message:\n`
> 
> https://github.com/rooch-network/rooch/blob/46dedc44f88f31994ec3ec41f2fc039357e8a01b/frameworks/rooch-framework/sources/auth_validator/auth_payload.move#L11-L12
> 
> We can wrap it into a struct, like `AuthPayload`, and we need to ensure the signed result is the same as the Bitcoin wallet result.
> 
> 2. Provide a verify command and verify message move function.
> 
> @feliciss

It doesn't relate to any message signing format of the Bitcoin-QT or the RFC2440 on the wiki mentioned there: https://en.bitcoin.it/wiki/Message_signing#Displaying_signed_messages.
