### ISSUE TITLE
[Gas] Global notification mechanism for Gas schedule upgrade events.

### ISSUE THREAD

**Issue by steelgeek091** [rooch-network/rooch#2399]
There should be a global, thread-safe, asynchronous, and easy-to-use subscription and notification mechanism to notify multiple subscribers when a Gas upgrade event occurs. 

Subscribers can be any function, either in the current thread or in other threads.

**Comment by jolestar** [comment]
Implement an event bus actor, and other actors publish the events to or subscribe events from the event bus.
