### ISSUE TITLE
[genesis] Rename  Rooch GasCoin  symbol to  RGas

### ISSUE THREAD

**Issue by jolestar** [rooch-network/rooch#2419]
- [ ]  RGas is the symbol of Rooch Gas Coin. Should we rename the module name?
- [ ] Design an icon for RGas

**Comment by feliciss** [comment]
I can handle this.

**Comment by jolestar** [comment]
> I can handle this.

Please wait until we prepare to reset the genesis.

**Comment by baichuan3** [comment]
both rename symbol and rename module, will break dapps and sdk
