### ISSUE TITLE
typescript sdk bug 

### ISSUE THREAD

**Issue by v1xingyue** [rooch-network/rooch#2481]
### Rooch version

rooch 0.6.8 (git commit 82899480bd5fe65b0d7c5502ccf62f010e878b16)

### What did you do?

When I did clear session by ts sdk, sometimes comes out error. When I checking the localstorage , it seems I have 2 sessions. At that time when I clear session it will tell error : 

![image](https://github.com/user-attachments/assets/bb306255-4cb7-482b-b503-58aee6a7a215)

### What did you see happen?

![image](https://github.com/user-attachments/assets/9ca75449-223a-451b-84dd-0875b89a6f8a)

### What did you expect to see?

I want it clean well. And the session should have only one.

**Comment by newraina** [comment]
can I take this issue?

**Comment by newraina** [comment]
Potential Scenarios Leading to Similar Issues:

1. Switching networks, where sessions from other networks remain locally (to be discussed in separate issues)
2. The session has already been removed via the portal
3. The session has expired

This issue focuses on handling scenarios 2 and 3.

**Actions to be Taken:**

1. When an expired error is encountered, the SDK should clear the corresponding session from local storage, not just from memory.
2. When retrieving the current session from local storage, the SDK should exclude any value that has expired, based on maxInactiveInterval + lastActiveTime.
3. The application itself should handle expiration logic as well. A reference for this can be add in the template (#2531).
