### ISSUE TITLE
error[E0412]: cannot find type `siginfo_t` in crate `libc`

### ISSUE THREAD

**Issue by summertoo** [rooch-network/rooch#2494]
### Rooch version

0.6.8

### What did you do?

cargo build (Windows 11)

### What did you see happen?

![image](https://github.com/user-attachments/assets/b4f40f3c-55bb-473a-ab16-828e873b587a)

### What did you expect to see?

有没有大佬解决这个问题?

**Comment by jolestar** [comment]
#1667

**Comment by summertoo** [comment]
> #1667

嗯 对的 可以合并成一个问题

**Comment by jolestar** [comment]
Close this issue, tracked via #1667
