### ISSUE TITLE
[Testing] Test cases for runtime entry function verification.

### ISSUE THREAD

**Issue by steelgeek091** [rooch-network/rooch#252]
We should write test cases for `runtime verification of the entry function`. 
These test cases can be divided into two categories: `successful verification` and `failed verification`. 
Additionally, multiple test scenarios should be constructed for each category.

Reference the Move test cases at: https://github.com/move-language/move/tree/main/language/move-bytecode-verifier/transactional-tests/tests.

For example:
- entry_function_with_return_value.move
- entry_function_invalid_struct.move
- entry_function_valid_struct.move
- entry_function_invalid_reference.move

In the Rooch project, we can write the test code in this directory: `crates/rooch-integration-test-runner/tests/cases`.

**Comment by feliciss** [comment]
Can I try with this issue?

**Comment by steelgeek091** [comment]
> Can I try with this issue?

Sorry, this issue is currently assigned to @WGB5445. Are you interested in working on this issue https://github.com/rooch-network/rooch/issues/265?
