### ISSUE TITLE
[cli] change the bitcoin public key output to hex

### ISSUE THREAD

**Issue by jolestar** [rooch-network/rooch#2527]
### Proposal Details

Change the bitcoin public key output in `rooch account list` from base58 to hex format

**Comment by huisq** [comment]
[line50](https://github.com/rooch-network/rooch/blob/419b94572ac381b7b256861ca92ba520dec889c6/crates/rooch/src/commands/account/commands/list.rs#L50)-> public_key: hex::encode(account.public_key)

**Comment by feliciss** [comment]
May I handle this issue?

**Comment by jolestar** [comment]
> May I handle this issue?

fixed in #2552
