### ISSUE TITLE
Writing compile-time test cases for the verifier's function should be supported in the rooch-integration-test-runner.

### ISSUE THREAD

**Issue by steelgeek091** [rooch-network/rooch#254]
In `crates/rooch-integration-test-runner/tests`, only the `CompiledModule` after compilation can be checked, and checking the `ModuleEnv` during compilation is not supported. Therefore, it is not possible to write test cases for `compile-time verification`.

**Comment by feliciss** [comment]
I may dig into this later time possibly with moveos-compiler?

**Comment by jolestar** [comment]
Is this issue resolved?

**Comment by steelgeek091** [comment]
> Is this issue resolved?

Yes, the test cases has been resolved.
