### ISSUE TITLE
[CLI] Add a suffix to multisign psrt file

### ISSUE THREAD

**Issue by jolestar** [rooch-network/rooch#2589]
### Proposal Details

When using `rooch tx sign` to sign a multisign tx, the command will generate a `psrt` file.

We can add a suffix to the file to distinguish how many participants have signed the tx.

`[tx_hash_prefix].[signature_cout].psrt`,

eg: `e93f585e5a24a667-1.psrt` is the first signature of e93f585e5a24a667.

**Comment by feliciss** [comment]
I can handle this issue.
