### ISSUE TITLE
Panic found, System call panic Execute system call with Panic Some

### ISSUE THREAD

**Issue by yourmoonlight** [rooch-network/rooch#2590]
### Rooch version

rooch:v0.7.0

### What did you do?

found some server panic log 

### What did you see happen?

[2m2024-09-07T00:48:52.428667Z[0m [31mERROR[0m [2mrooch_rpc_server[0m[2m:[0m System call panic Execute system call with Panic Some(VMErrorInfo { error_message: "VMError with status ABORTED with sub status 1 at location Module ModuleId { address: 0000000000000000000000000000000000000000000000000000000000000002, name: Identifier(\"object\") } at code offset 0 in function definition 40", execution_state: [] })

### What did you expect to see?

no panic

**Comment by wow-sven** [comment]
link this?
<img width="996" alt="image" src="https://github.com/user-attachments/assets/6faf7ff0-db6d-466b-be20-cd519ce0c4c1">

**Comment by jolestar** [comment]
Does the reorg cause this panic?  @baichuan3 @steelgeek091

**Comment by baichuan3** [comment]
> like this? <img alt="image" width="996" src="https://private-user-images.githubusercontent.com/6805130/365382886-6faf7ff0-db6d-466b-be20-cd519ce0c4c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4NTQwMTcsIm5iZiI6MTcyNTg1MzcxNywicGF0aCI6Ii82ODA1MTMwLzM2NTM4Mjg4Ni02ZmFmN2ZmMC1kYjZkLTQ2NmItYmUyMC1jZDUxOWNlMGM0YzEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDlUMDM0ODM3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGZiMzIxNDAxZDg1NzdjMzc2NzAxZGRkZmI5MGU5MjRiNjUxMGRlMDY3ODdkYWRmYmEwNWYyMmUyZTViOTM0YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.1cBd55bo--FOonTyWL6kqJinx16LLXqoaQezCcQkXps">

Which environment are you using? testnet or local?

**Comment by steelgeek091** [comment]
> Does the reorg cause this panic? @baichuan3 @steelgeek091

Use the local environment can trigger this error information.

**Comment by jolestar** [comment]
The case from @wow-sven should be fixed in #2599
