### ISSUE TITLE
[GasProfiling] Use FlameGraph to display gas consumption during the transaction execution process.

### ISSUE THREAD

**Issue by steelgeek091** [rooch-network/rooch#2598]
Use a specialized GasMeter to track gas consumption for basic instructions, storage, and function calls during a transaction. Then, use FlameGraph to display the gas consumption data in the form of a function call stack.

Implement Tasks:

- [ ] Gas statistics for basic instructions, storage, and function calls execution.
- [ ] Management of function CallFrame and gas event tracking.
- [ ] Generate and display a FlameGraph from existing data.

**Comment by jolestar** [comment]
Is this issue finished?

**Comment by steelgeek091** [comment]
> Is this issue finished?

already finished.
