### ISSUE TITLE
[Reorg] Optmize rerog handling

### ISSUE THREAD

**Issue by baichuan3** [rooch-network/rooch#2610]
### Proposal Details

The probability of testnet reorg being greater than 3 blocks is still very high, and optimization is needed
1. After Reorg Panic, Rooch Server needs to be automatically set to read-only mode;
2. Testnet Reorg pending blocks, it is recommended to adjust from 3 to 5

**Comment by feliciss** [comment]
Is this issue available for resolving? I'm interested in it but do not think I could handle it at this time.
