### ISSUE TITLE
query resource bug 

### ISSUE THREAD

**Issue by v1xingyue** [rooch-network/rooch#2753]
### Rooch version

rooch 0.7.3

### What did you do?

I use client sdk query resource data:

```typescript
const resource = await client.getStates({
        accessPath: `/resource/${mypackage}/${mypackage}::swap::Pool<${mypackage}::rhec_coin::RHEC,0x3::gas_coin::RGas>`,
        stateOption: {
          decode: true,
        },
      });


```

In fact browser pass query json : 

```
{"jsonrpc":"2.0","id":1,"method":"rooch_getStates","params":["/resource/0x726b3e4cdbcd2e0cd0d5916bc3f8ce0970760e3d048b5ab0e84766c68a72fb9b/0x726b3e4cdbcd2e0cd0d5916bc3f8ce0970760e3d048b5ab0e84766c68a72fb9b::swap::Pool<0x726b3e4cdbcd2e0cd0d5916bc3f8ce0970760e3d048b5ab0e84766c68a72fb9b::rhec_coin::RHEC,0x3::gas_coin::RGas>",{"decode":true}]}
```

### What did you see happen?

it return error : 

```
{
    "jsonrpc": "2.0",
    "error": {
        "code": -32602,
        "message": "Invalid params",
        "data": "invalid struct tag: 0x726b3e4cdbcd2e0cd0d5916bc3f8ce0970760e3d048b5ab0e84766c68a72fb9b::swap::Pool<0x726b3e4cdbcd2e0cd0d5916bc3f8ce0970760e3d048b5ab0e84766c68a72fb9b::rhec_coin::RHEC, expected token Comma, got EOF"
    },
    "id": 1
}
```

### What did you expect to see?

get the resource data.

**Comment by jolestar** [comment]
We use the `,` to split the multi-resource query `/resource/sturct_tag1,struct_tag2`, but the `,` also splits multi-param types. There is a conflicting usage. Should we not support the multi-resource query? `/resource/` AccessPath only supports one StructTag.

https://github.com/rooch-network/rooch/blob/11dc8ab618b68451cae76105b7ca3724c93aecf3/moveos/moveos-types/src/access_path.rs#L164-L169

cc @pause125 @vegetabledogdog

**Comment by v1xingyue** [comment]
> We use the `,` to split the multi-resource query `/resource/sturct_tag1,struct_tag2`, but the `,` also splits multi-param types. There is a conflicting usage. Should we not support the multi-resource query? `/resource/` AccessPath only supports one StructTag.
> 
> https://github.com/rooch-network/rooch/blob/11dc8ab618b68451cae76105b7ca3724c93aecf3/moveos/moveos-types/src/access_path.rs#L164-L169
> 
> cc @pause125 @vegetabledogdog

Shell we consider use other letters will not used by struct type define, such as `|` .
