### ISSUE TITLE
proposal(db):  persist revert process for indexer updates

### ISSUE THREAD

**Issue by popcnt1** [rooch-network/rooch#2769]
### issue:
When collapse happen between rooch-db and indexer revert/rollback, indexer may lost needed updates

#### reproduce steps:
1. revert sequencer and executor done
2. collapse
3. inconsistence happens between rooch-db and indexer

### approach:

For online revert, it'll only be triggered by failed execution. which means there is no changeset at all, so there is nothing to do with indexer.

For offline revert:

1. persist tx_order, tx_hash, changeset as job after rever rooch-db
2. process indexer rever 
3. after indexer updated, delete job
5. replay indexer update if there is undone job

### implementation:
1. ensure revert/rollback rooch-db is consistent, which has been added in: #2768 
2. we could persist these info locally just for rooch-db command. That's enough for most cases, even in tx executor processor, because in executor, failed tx would create changeset, there is nothing to do with indexer in revert process. @baichuan3 am I right about this?

**Comment by baichuan3** [comment]
Only when writing sequence info but no execute info, there is nothing to do with the indexer.

**Comment by popcnt1** [comment]
> Only when writing sequence info but no execute info, there is nothing to do with the indexer.

So only implement persistence info for revert/rollback locally is enough.

For online processor, we only need to revert tx when it cannot be executed properly, which means there is no execution info

**Comment by popcnt1** [comment]
#1409
