### ISSUE TITLE
proposal: unify log dep for online server

### ISSUE THREAD

**Issue by popcnt1** [rooch-network/rooch#2810]
### Proposal Details

I've found log/tracing are mixed up, e.g.:

In rooch-executor/src/actor/executor.rs: log::warn! tracing::warn!  are mixed

p.s.

For testnet, We've found there is a tx_hash lost its ledgerTx. So we should see a error log but not. Is it related to this issue?

**Comment by jolestar** [comment]
unify all log to `tracing`
