### ISSUE TITLE
[cli] `rooch move publish` support publish a rpd file 

### ISSUE THREAD

**Issue by jolestar** [rooch-network/rooch#2826]
### Proposal Details

The developer can directly publish a rpd file.

```
rooch move publish ./build/myapp/package.rpd
```

`rooch move publish` == `rooch move build` -> `package.rpd` and `rooch move publish package.rpd`

```bash
rooch move run --function 0x2::module_store::publish_package_entry --args file:./build/myapp/package.rpd
```

**Comment by wfnuser** [comment]
I'd like to have a try.
