### ISSUE TITLE
[API] Error when using short hex string in AccessPath

### ISSUE THREAD

**Issue by wubuku** [rooch-network/rooch#284]
Current APIs (e.g., get status, events) return bytes in hex as short hex, which means that the number of characters in hex may be odd because the leading zeros are removed.

Developers are likely to use these short hex strings directly in subsequent requests, for example as part of the AccessPath.

If AccessPath does not support short hex, it will obviously increase the burden on developers. So it is recommended that AccessPath support short hex.

**Comment by jolestar** [comment]
We need to ensure the ObjectID and Address use the full length hex output.

**Comment by wubuku** [comment]
Now the access path supports compressed short hex, but the places where I added a 0 in front of the hex (when it was an odd number of characters) to make the unit test passable didn't work now. 😂

Both short hex and regular hex should be supported.

**Comment by jolestar** [comment]
> Now the access path supports compressed short hex, but the places where I added a 0 in front of the hex (when it was an odd number of characters) to make the unit test passable didn't work now. 😂
> 
> Both short hex and regular hex should be supported.

Please give an test example
