### ISSUE TITLE
proposal: [processor]: load L1Block tx from local filesystem to repair database states on startup 

### ISSUE THREAD

**Issue by popcnt1** [rooch-network/rooch#2844]
### Proposal Details

Background:

sequenced tx and executed tx are persisted by two atomic writes, when sequenced tx written but executed tx not, we have to re-execute it on startup for local transaction store. 

But for L1Block tx, we only keep block meta but not body on local disk. So we have to find a way to pass L1 Block data.

Approach:

When we meet the startup error caused by lacking L1Block tx, we could make it on local. Processor could load these local data to re-execute L1 Block tx.

**Comment by jolestar** [comment]
We already write the L1 Block and tx to Move contract, we can directly re-execute it.
