### ISSUE TITLE
Security Report for Rooch Project

### ISSUE THREAD

**Issue by steelgeek091** [rooch-network/rooch#2850]
As of now, we have received and fixed 7 security reports in total, comprising 2 high-risk vulnerabilities and 5 low-risk vulnerabilities. We take code security very seriously and have made these 7 security reports public, encouraging everyone to actively participate in the security audit of Rooch codebase.

**High-Risk Vulnerability:**

1. [合约方法`vector<Object<MockObject>>`传入一个不存在的object或者其他用户的object可以绕过检测。](https://github.com/rooch-network/rooch/security/advisories/GHSA-2mh8-rvf9-mq47) by @qShirley
2. [Object状态查询接口对于参数 ObjectID 的数量未限制导致大量内存占用进程退出。](https://github.com/rooch-network/rooch/security/advisories/GHSA-q7jw-699g-rrxf) by @m4sterchain

----

**Low-Risk Vulnerability:**

1. [Rooch RPC Server 使用不规范的方式使用 **assert_eq!** 宏可能导致进程异常。](https://github.com/rooch-network/rooch/security/advisories/GHSA-6m8m-m9g8-rj43)  by @nathanogaga118 
2. [解析 BitCoin 地址时未处理的异常可能导致进程停止服务。](https://github.com/rooch-network/rooch/security/advisories/GHSA-r68j-jvr6-cxwv)  by @nathanogaga118
3. [处理交易回滚时异常中断可能导致状态数据不一致。](https://github.com/rooch-network/rooch/security/advisories/GHSA-x8fq-xcrv-qc8r) by @nathanogaga118
4. [解析 BitCoin 地址时未检测空地址导致进程异常。](https://github.com/rooch-network/rooch/issues/2247) by @pause125 
5. [解析 struct_tag 不正确的逻辑导致进程异常。](https://github.com/rooch-network/rooch/issues/2394) by @qShirley

**Comment by steelgeek091** [comment]
If you see this information, please contact us by leaving a message here. @m4sterchain

**Comment by nathanogaga118** [comment]
thank you team, yes I received the message

**Comment by m4sterchain** [comment]
> @m4sterchain If you see this information, please contact us by leaving a message here.

Hi @steelgeek091 , thanks for the information.

**Comment by flyliyiyun** [comment]
Hi@m4sterchain ，The rewards of bug bounty are on the registration process. Can you share your email address here？ Or send the message to 0xchristinali@rooch.network. Looking forward to hearing from you.

**Comment by m4sterchain** [comment]
> Hi @m4sterchain ，The rewards of bug bounty are on the registration process. Can you share your email address here？ Or send the message to [0xchristinali@rooch.network](mailto:0xchristinali@rooch.network). Looking forward to hearing from you.

Hi @flyliyiyun , thanks for the update. I have sent you an email for connection.
