### ISSUE TITLE
rooch move run --dry-run flag did't work

### ISSUE THREAD

**Issue by YouNeedWork** [rooch-network/rooch#2874]
### Rooch version

rooch 0.7.6 (git commit e5ba2429862ad18b84e283cffa13ac99b49a71d7)

### What did you do?

❯ rooch move run --function $PKG::gold_miner::start --args "object:$TREASURY" --args "address:$SENDER" --dry-run

### What did you see happen?

Error: Parse error: missing field `da_server_status` at line 1 column 1687
missing field `da_server_status` at line 1 column 1687

### What did you expect to see?

正常返回输出信息

**Comment by jolestar** [comment]
The mainnet need to be upgrade. cc @popcnt1 @steelgeek091

**Comment by jolestar** [comment]
fixed
