### ISSUE TITLE
[Bug] Error when building the example project private_generics

### ISSUE THREAD

**Issue by pause125** [rooch-network/rooch#289]
Failed to build the example project `examples/private_generics`.

The error message:
```
BUILDING private_generics
error: resource type "U64" in function "0x123::Data::create_box" not defined in current module or not allowed
   ┌─ ./sources/private_generics.move:21:23
   │
21 │         let box_val = create_box<Data, u64, Box<u32>>(data);
   │                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

extended checks failed
```
Reproduce:

run `cargo run --bin rooch move build -p examples/private_generics`

@steelgeek091

**Comment by feliciss** [comment]
I think the primary reason for this is the build-in type variable `u64`, because the inherences of that, types are not resources so the error.

**Comment by feliciss** [comment]
If we define arbitrary struct as resources, say 

```rust
struct Data2 {}
```

and put into the generics:

```rust
let box_val = create_box<Data, Data2, Box<u32>>(data);
```

It will work.

The mistake that @steelgeek091 made is the mishandling of types and resources (as structs, in most cases).

**Comment by feliciss** [comment]
Reference:

https://move-language.github.io/move/structs-and-resources.html?highlight=resource#structs-and-resources

**Comment by steelgeek091** [comment]
> If we define arbitrary struct as resources, say
> 
> ```rust
> struct Data2 {}
> ```
> 
> and put into the generics:
> 
> ```rust
> let box_val = create_box<Data, Data2, Box<u32>>(data);
> ```
> 
> It will work.
> 
> The mistake that @steelgeek091 made is the mishandling of types and resources (as structs, in most cases).

Yes, the generic parameters of private_generics do not support primitive types. They only support structs and generic struct types.
https://github.com/rooch-network/rooch/blob/main/moveos/moveos-verifier/src/metadata.rs#L466
