### ISSUE TITLE
[Example] Add test case for private generics in the examples directory.

### ISSUE THREAD

**Issue by feliciss** [rooch-network/rooch#296]
Add test case for #289

**Comment by jolestar** [comment]
the test case should not be put in the `example` dir. It should be in the `rooch-framework-tests`

**Comment by jolestar** [comment]
> the test case should not be put in the `example` dir. It should be in the `rooch-framework-tests`

It is ok to put in the example's integration-tests dir.

**Comment by feliciss** [comment]
> > the test case should not be put in the `example` dir. It should be in the `rooch-framework-tests`
> 
> It is ok to put in the example's integration-tests dir.

Like these two test cases?
```
examples/counter/integration-tests/counter.exp
examples/counter/integration-tests/counter.move
```
And we should also write test cases in `rooch-framework-tests` for unit tests and `rooch-integration-test-runner` for integration tests?

**Comment by feliciss** [comment]
> I think the `private_generics` integration tests should be in the `rooch-framework-tests`, The `private_generics` example is a demo for giving application developers, showing how to use the `private_generics`.
> 
> `rooch-integration-test-runner`'s test cases just for test the runner self.

Got it.

**Comment by jolestar** [comment]
Close this; feel free to reopen it if it is still needed.
