### ISSUE TITLE
proposal: genesis-config: set a larger bitcoin_reorg_block_count for bitcoin testnet

### ISSUE THREAD

**Issue by popcnt1** [rooch-network/rooch#3080]
### Proposal Details

background: 

1. bitcoin testnet produce block in avg 1.5min/block 
2. bitcoin mainnet produce block in avg 10min/block 
3. bitcoin mannet bitcoin_reorg_block_count is 3, about 30mins 
4. bitcoin testnet bitcoin_reorg_block_count is 5, about 7.5mins 
5. Historically, we have paused the rooch network several times due to testnet reorg exceeding the threshold， and fixed it by rolling back a large number of transactions.This suggests that our original parameters did not meet our expectations for downtime

approach:

set a larger bitcoin_reorg_block_count for bitcoin testnet

**Comment by jolestar** [comment]
update to 10 

tx_hash: 0x4261172aa69d2623f440aa6411df10971e7e1aced7957e7996a9f2cef594a8f8
