### ISSUE TITLE
Rooch zh docs style convention

### ISSUE THREAD

**Issue by geometryolife** [rooch-network/rooch#312]
关于 Rooch 中英文混排的文档中，一些翻译、排版风格的讨论：

1. 在括号中用英文解释一些名词（组）时，英文单词使用`开头大写`还是`统一小写`
1）对普通名词
- ……能力（Ability）……
- ……能力（ability）……
2）对专有名词的解释，采取哪一种约定
- 存储抽象（Storage Abstraction）
- 存储抽象（storage abstraction）

2. 文档的标题是否直接使用中文即可，而不需要在标题后使用`（英文）`来解释
3. 关于常见词是否翻译
- `Object` -> `对象`
- `Key` -> `键`
- `Value` -> `值`
- `Key-Value pairs` -> `键-值对`、`Key-Value 对` 或 `K-V 对`

**Comment by geometryolife** [comment]
我们找个例子 #311 来聊聊

**Comment by templexxx** [comment]
1专有名词首字母还是大写
2 是啥意思？没看懂
3 常见技术用词还是英文吧 方便 代码 文档 技术文章等统一查询和理解

**Comment by geometryolife** [comment]
> 1专有名词首字母还是大写 2 是啥意思？没看懂 3 常见技术用词还是英文吧 方便 代码 文档 技术文章等统一查询和理解

![image](https://github.com/rooch-network/rooch/assets/54882546/3151d489-4d22-477b-b110-946280fdb679)
2 是指这个地方，以前翻译 Move Book 时就是使用这种形式，但是发现引用时，不是很方便，之后标题就只留中文而不加一个括号来用英文解释了

**Comment by templexxx** [comment]
> > 1专有名词首字母还是大写 2 是啥意思？没看懂 3 常见技术用词还是英文吧 方便 代码 文档 技术文章等统一查询和理解
> 
> 
> 
> ![image](https://github.com/rooch-network/rooch/assets/54882546/3151d489-4d22-477b-b110-946280fdb679)
> 
> 2 是指这个地方，以前翻译 Move Book 时就是使用这种形式，但是发现引用时，不是很方便，之后标题就只留中文而不加一个括号来用英文解释了

明白了。这种就不要括号了

**Comment by jolestar** [comment]
1. 开头大写
2. 标题后使用（英文）来解释一般是中文的词汇认知还不够，但如果是为了引用的问题可以不要。括号放在段落内容里就行。
3. 常见词干脆就不翻译了。
