### ISSUE TITLE
[modules] customized modules not detected. 

### ISSUE THREAD

**Issue by feliciss** [rooch-network/rooch#340]
First seen in [the CI](https://github.com/rooch-network/rooch/actions/runs/5339575230/jobs/9678409347) as:

```
task 3 'view'. lines 26-28:
key 0x42::test::Foo {
    x: 500
}
[No Resource Exists]
```

To debug, In line 11-13 in publish_cmd.move, 

```rust
public fun publish_foo(ctx: &mut StorageContext, s: &signer) {
        account_storage::global_move_to<Foo>(ctx, s, Foo { x: 500 })
}
```

`global_move_to` has no effects called from rooch module account_storage. Thus the lines

```
//# view
//#     --address 0x42
//#     --resource 0x42::test::Foo
```

are invalid.

Unknown error. Discussion on Discord:

https://discord.com/channels/1078938449974935592/1078945780309708800/1123272247390519306

**Comment by feliciss** [comment]
It might be a bug on the CI side.

**Comment by feliciss** [comment]
The error usually comes from out of scope in move, which means the customized module import failed.

**Comment by jolestar** [comment]
this issue is resolved?

**Comment by feliciss** [comment]
> this issue is resolved?

I think no. Should detect if there's unbound error when running tests.

**Comment by feliciss** [comment]
Similar issue of #404. Close this one.
