### ISSUE TITLE
[MoveosStd] Table need provide destroy_empty_table, is_empty and length function 

### ISSUE THREAD

**Issue by jolestar** [rooch-network/rooch#342]
1. Whether to record length and where to record it. It doesn't feel right to keep the record in TableHandle. If it is recorded in TableInfo, how to get TableInfo is a problem (TableInfo is in ObjectStorage, there is a dependency cycle problem).
2. The StateResolver trait of Table only has the method of obtaining value through ObjectID(TableHandle) and key. How to express and obtain table length, or check `is_empty` is also a problem.

### Refs

1. Discussion: https://discord.com/channels/1078938449974935592/1121436866890170398

**Comment by jolestar** [comment]
Two solutions:

1. Save length in `Table`, `TypeTable`, and `ObjectStorage`, like in Move's Table extension or Aptos's TableWithLength. The advantage is that it is easy to implement and can be implemented directly in Move without native or statedb support. The disadvantage is that the struct with a table as field, after modifications to the Table, the struct will also change.

2. Implement a native method to check if the Table is empty. However, this check cannot directly rely on statedb since the VM runtime does not update statedb in real-time. It requires the Table's Runtime cache and statedb to work together. In this case, we also need to save a length, which can be stored in the TableInfo. TableInfo is a global Object, currently only saving the Table SMT's state_root, which will be directly updated and created by StateDB. raw_table native does not know TableInfo. We need to refactor the raw_table runtime implemention.

**Comment by pause125** [comment]
For option 1, as [this](https://github.com/rooch-network/rooch/blob/d8f75a09f80731fb006fc441fe9fbc1c40dd4499/moveos/moveos-stdlib/moveos-stdlib/sources/table.move#L28C93-L28C93) function can create a table from a given handle,  the init length may no longer be zero, there should have a way to get the length of the given handle.
