### ISSUE TITLE
[exp] file formats

### ISSUE THREAD

**Issue by feliciss** [rooch-network/rooch#346]
When generating exp files, there are automated formats generated from the test runner. However, issues remain at alarming level especially mishandled with "Enter" or "White Space" at the end of the exp files.

For example:

1. This test would succeed with a new line at the EOF:

```
processed 2 tasks

task 1 'publish'. lines 3-13:
status EXECUTED

```

2. This test wouldn't:

```
processed 2 tasks

task 1 'publish'. lines 3-13:
status EXECUTED
```

Similarly:

1. Successful:

```
processed 2 tasks

task 1 'publish'. lines 3-7:
Error: error: type name "T2" not defined in function "create_box"
  ┌─ /tmp/tempfile:6:5
  │
6 │     public fun create_box<T1>() {}
  │     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^



```

2. Failure:

```
processed 2 tasks

task 1 'publish'. lines 3-7:
Error: error: type name "T2" not defined in function "create_box"
  ┌─ /tmp/tempfile:6:5
  │
6 │     public fun create_box<T1>() {}
  │     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Due to the absence of exp formatter, I suggest we compile a one and submit a request to https://github.com/move-language/move.

Ref: https://github.com/move-language/move/issues/166

**Comment by jolestar** [comment]
So, the solution is to trim the end new line and white space? The exp file is auto generate by the test, so developers should rarely encounter this issue.

**Comment by feliciss** [comment]
> So, the solution is to trim the end new line and white space? The exp file is auto generate by the test, so developers should rarely encounter this issue.

Not really. Only `rooch move integration-test` command will generate exp files. Other exp files, such those in the `rooch-framework-tests` and `rooch-integration-test-runner` are run by the command `cargo test`.

And yes, based on the above assumptions, examples for developers will cause no problems because the exp files are generated from `rooch move` command and thus end-users and -developers friendly.

Also no. We, rooch developers will have to handle trimming new lines and white spaces for exp files in the `crates` directory.

**Comment by jolestar** [comment]
Set env `UB=1` to generate the exp file.

```bash
UB=1 cargo test
```
We need a document to describe how to write integration tests.

**Comment by feliciss** [comment]
> Set env `UB=1` to generate the exp file.
> 
> ```shell
> UB=1 cargo test
> ```
> 
> We need a document to describe how to write integration tests.

I set it before, but it seemed it didn't work.

I will retest if I could run `cargo test` in current main branch. The main branch breaks now.

**Comment by feliciss** [comment]
Something notable:

```zsh
test panicked: called `Result::unwrap()` on an `Err` value: Custom { kind: Uncategorized, error: PathError { path: "/var/folders/30/bf9thrdx4q58bzsk7xg3sbtw0000gn/T/.tmpQw9MUJ", err: Os { code: 24, kind: Uncategorized, message: "Too many open files" } } }
```

**Comment by jolestar** [comment]
setting the os config
