### ISSUE TITLE
[Genesis] Include the genesis binary to rooch binary

### ISSUE THREAD

**Issue by jolestar** [rooch-network/rooch#393]
We auto-build the genesis when `rooch server start`, but the build depends on the Move stdlib and framework source code. If we run the release binary on a device which not have the Rooch source code in the special location(It must be the same as the release device), the server can not be started. #391 

So, we have two options:

1. Auto-include the Move source code in Rooch's binary.
2. Build a genesis binary and include the genesis binary in Rooch's binary. 

# Reference

* Discussion: https://discord.com/channels/1078938449974935592/1125246381381124176
* Starcoin Genesis build: https://github.com/starcoinorg/starcoin/blob/master/genesis/src/main.rs

**Comment by feliciss** [comment]
> 1. Auto include the Move source code in rooch's binary.

This can be a tremendous work, especially when the source code becomes large.

> 2. Build a genesis binary and include the genesis binary in rooch's binary.

I suggest doing this way, as well as other project did, e.g. Hyperledger Fabric.

**Comment by jolestar** [comment]
Solution: provide two Genesis build methods:

1. Fresh: Build genesis directly from the source code, requiring the local machine to have the rooch source code.
2. Release: Load the genesis binary directly.

It is automatically determined according to the profile of the rust release. If it is debug mode, use 1, if it is release mode, use 2. 

In this way, there is no need to include the Move source code, and there is no need to restore the source code to the local.
