### ISSUE TITLE
Basic Sequencer Interfaces

### ISSUE THREAD

**Issue by jolestar** [rooch-network/rooch#41]
- [ ] Ordering: User-facing Sequencer Interface (+ order witness)
- [ ] Execution: Query Interface 
- [ ] I/O: Persistence Interface

**Comment by steelgeek091** [comment]
## Ordering: User-facing Sequencer Interface (+ ordering witness)

**1. SendTransaction to the sequencer and get return ordering witness response from the sequencer.**

**URL:**
```txt
/v1/sequencer/send_tx
```

**Method:**

```
POST
```

**Request:**

```rust
struct {
	sender_address: String,
	public_key: Vec<u8>,
	program: Vec<u8>,
	sequencer_number: u64,
	expiration_time: u64,
	signature: Vec<u8>
}
```

**Response:**

```rust
struct {
	transaction_hash: String,
	ordering_witness: Vec<u8>
}
```

**2. The user verifies that their transaction conforms to the order guaranteed by the sequencer.**

**URL:**
```txt
/v1/sequencer/verify_tx
```

**Method:**

```
POST
```

**Request:**

```rust
struct {
	transaction_hash: String,
	ordering_witness: Vec<u8>
}
```

**Response:**

```rust
struct {
	verify_result: Vec<u8>
}
```

**Comment by jolestar** [comment]
I think we need to define the Rust trait first and design a transaction flow between components.

**Comment by templexxx** [comment]
some suggestions @steelgeek091 

1. transaction -> txn
2. sequencer_signature -> txn_order_signature: means sign the txn order
3. order_witness -> txn_order_witness: same strucuture as order_signature

p.s.

In computer science, and cryptographic, using witness as proof or part of proof is common, so this word is okay. The original name "sequence proof" may conflict with "sequence" in other places.

**Comment by jolestar** [comment]
Sequencer basic implementation in #158 

Transaction RPC tracked by #229 
Sequence Proof and RPC tracked by #228 (v0.2)
Transaction storage tracked by #157 

Close this issue.
