### ISSUE TITLE
[RPC] provide an API to simulate running the transaction

### ISSUE THREAD

**Issue by jolestar** [rooch-network/rooch#422]
Provide an API to simulate running the transaction and get the transaction ChangeSet, Event, and TransactionExecutionInfo(GasUsed).

## Refs

* Aptos `transactions/simulate`: https://aptos.dev/nodes/aptos-api-spec#/
* Starcoin `contract.dry_run` : https://github.com/starcoinorg/starcoin/blob/5772b323b08397875a3a0806307d7f6f6f735476/rpc/api/src/contract_api.rs#L35

**Comment by yubing744** [comment]
I want to try this task so that I can become more familiar with the storage of Rooch status, which will facilitate game status synchronization later.

**Comment by jolestar** [comment]
#2380
