### ISSUE TITLE
[Framework] Bitcoin light client with Move

### ISSUE THREAD

**Issue by jolestar** [rooch-network/rooch#423]
Implement a Bitcoin light client with Move.

1. Receive a Bitcoin header from the entry function argument.
2. Decode the header.
3. Verify the header via Nakamoto Consensus (Difficulty and the Longest Chain).
4. Record the header to state.
5. Provide a function to verify the transaction Merkle proof.

**Comment by feliciss** [comment]
I'm interested in this issue. However, I may complete issue #406 first.

**Comment by jolestar** [comment]
Now, we implement a full Bitcoin client in Move. the verifier Header requirement tracked via #1330
