### ISSUE TITLE
[MoveosStd]  constraints of event::emit_event T

### ISSUE THREAD

**Issue by jolestar** [rooch-network/rooch#440]
```move
public fun emit_event<T: key>(ctx: &mut StorageContext, event: T);
```

1. Is the `T` need the `key` ability?
2. Should add `private_generics<T>` to the emit_event

@steelgeek091  @baichuan3

**Comment by baichuan3** [comment]
> ```move
> public fun emit_event<T: key>(ctx: &mut StorageContext, event: T);
> ```
> 
> 1. Is the `T` need the `key` ability?
> 2. Should add `private_generics<T>` to the emit_event
> 
> @shelmesky @baichuan3

1, remove the `key` ability for `T `
2, add `private_generics<T>` to the emit_event  for restrict safe calls
