### ISSUE TITLE
AccountAbstraction (Compatible with ETH account)

### ISSUE THREAD

**Issue by yubing744** [rooch-network/rooch#45]

**Comment by baichuan3** [comment]
**Signature flow**
<img width="999" alt="image" src="https://user-images.githubusercontent.com/1904567/236368172-2bf59e0e-a286-43e1-b346-1d7931e7a9ac.png">

**Account Abstraction**
<img width="843" alt="image" src="https://user-images.githubusercontent.com/1904567/236368224-2ccb3ce8-f1b0-47c8-a397-a46e8e48c2e4.png">
