### ISSUE TITLE
[MovoeosStd] provide a function to get signer of module address

### ISSUE THREAD

**Issue by jolestar** [rooch-network/rooch#456]
If we provide a native function to get the signer of the module address.

```move
module moveos_std::signer{
   
   #[private_generics(T)]
   public native module_signer<T>(): signer;

}
```

It is safe because we use `private_generics` to restrict the T. 

This function can be used when a developer wants to `move_to` some resource to the module address account. It is also helpful for the resource account.

@steelgeek091  @baichuan3 @wow-sven

**Comment by steelgeek091** [comment]
> If we provide a native function to get the signer of the module address.
> 
> ```move
> module moveos_std::signer{
>    
>    #[private_generics(T)]
>    public native module_signer<T>(): signer;
> 
> }
> ```
> 
> It is safe because we use `private_generics` to restrict the T.
> 
> This function can be used when a developer wants to `move_to` some resource to the module address account. It is also helpful for the resource account.
> 
> @steelgeek091 @baichuan3 @wow-sven

The native `move_to` instruction is being removed, and the `private_generics` constraint has already been added to the `global_move_to` function in moveos_stdlib. What is the use case for this function?

**Comment by jolestar** [comment]
Example:

```move
let t = TestStruct{};
let signer = moveos_std::signer::module_signer<TestStruct>();
account_storage::global_move_to(ctx,&signer,t);
```

**Comment by jolestar** [comment]
or self_module_signer by @steelgeek091

**Comment by jolestar** [comment]
Add this feature to document #493
