### ISSUE TITLE
[crypto] support `schnorr` signature standard for nostr and bitcoin protocol

### ISSUE THREAD

**Issue by feliciss** [rooch-network/rooch#457]
Like `ECDSA` and `ED25519` signatures, we should also add supports for `Schnorr` signatures, verify the authenticity of `Schnorr` signatures, validate the signatures from the Rooch transaction validator in order to support crypto scheme validation for `Schnorr` in Move.

At the time of writing, nostr mainly uses `Schnorr` signatures for its events sig, public key, and encodings as described here:

https://github.com/nostr-protocol/nips/blob/7cd861c4d3c7a28d6b0d4ee26ad2a36fdb2670a5/01.md#events-and-signatures

Bitcoin also has proposal `BIP-340` to support `Schnorr` signatures as mentioned here:

https://bips.xyz/340

As a practical example is being built for nostr, there shall be added a crypto verification for `Schnorr` signatures.

Part of #406

**Comment by jolestar** [comment]
relative issue #460
