### ISSUE TITLE
[doc] delete old documents once new move module names are assigned.

### ISSUE THREAD

**Issue by feliciss** [rooch-network/rooch#474]
I lately renamed `secp256k1_validator.move` to `ecdsa_validator.move`. Document of `ecdsa_validator.move` was generated, but the old document `secp256k1_validator.md` was still there.

I needed to delete it manually.

We need to change the detection logic of documents to let it automatically deletes old documents.

**Comment by jolestar** [comment]
traced by #363

**Comment by feliciss** [comment]
> tracked by #363

Okay. Close this issue.
