### ISSUE TITLE
[framework] Timestamp based on multi-chain block time

### ISSUE THREAD

**Issue by jolestar** [rooch-network/rooch#534]
Provide timestamp based on multi-chain block time.

### Refs

1. #417 
2. #423 
3. #424
4. #779

**Comment by yng17b** [comment]
@jolestar could u explain more about this issue? 

1. How are timestamps based on Multichain? 
2. What is the objective of such an approach?

**Comment by jolestar** [comment]
Use L1's time as rooch time. The time verified by the light client.
