### ISSUE TITLE
[Example] A simple Blog system

### ISSUE THREAD

**Issue by jolestar** [rooch-network/rooch#54]

**Comment by wubuku** [comment]
@jolestar can assign this issue to me. I plan to develop this example using a low-code approach.

I have started working on a low-code tool based on Rooch. Here, I am trying to use this tool to generate Rooch Move contracts:  https://github.com/wubuku/Dapp-LCDP-Demo/tree/main/rooch-contracts

In these contract code files, those beginning with "<autogenerated>" comments are already generated from the model using the tool. What we ultimately aim to achieve is that, except for the "*_logic.move" files where developers need to provide the implementation of functions (i.e. business logic), all other code in these files will be generated by the tool. The domain model file can be found here: https://github.com/wubuku/Dapp-LCDP-Demo/blob/main/domain-model/rooch/rooch-blog.yaml

After completing these tasks, I will move this example to the "examples" directory in the Rooch repository for other developers to refer to.

**Comment by wubuku** [comment]
This example is now almost complete. The example is currently in the repository forked out: https://github.com/wubuku/rooch/tree/main/examples/blog_example

I have written a Chinese version of the README, and will re-test it after the recent improvements to MoveOS (support for table destroy methods, etc.) are basically completed, and then write an English version of the README, and then I can submit the PR.
