### ISSUE TITLE
[statedb] Implement AccessPath for StateDB and RPC state query

### ISSUE THREAD

**Issue by jolestar** [rooch-network/rooch#58]
## StateDB query path
 
`/object/$object_id/$field_index`

If the field is a table, we can continue to query the table by key
    
`/object/$object_id/$field_index/$key/$field_index`
 
### Example

1. Get the `AccountStorage` object, `AccountStorage` is an object with the account's address as ObjectID

`/object/0x1`
 
2. Get the `Account` Resource at 0x1 address. First, get the `AccountStorage` object, 
   then get the `Account` resource from `AccountStorage`'s first field `resources` table.
   The `Account` resource's key is its type `0x1::account::Account`.
    
`/object/0x1/0/0x1::account::Account`

3. Get the `account` module. The module id is `0x1::account`. First, get the `AccountStorage` object, then get the `account` module from `AccountStorage`'s second field `modules` table.
 
`/object/0x1/1/account

4. Get data from `MyKYStore` from account 0x42
    
```
  module 0x42::my_kvstore{
     struct MyKVStore has key, store{
         table: Table<String,String>,
     }
  }
```

`/object/0x42/0/0x42::my_keystore/MyKVStore/0/my_key`

4. Directly get the SMT table

`/smt@$state_root/$key` 

### Two Named Table AccessPath

* User Resources:  `/address/$address/resources/`
* User modules: `/address/$address/modules`

/address/$address/resources is a shortcut for:

First, get the resource table object by /object/$resource_table_id/, then list the table by  /smt/$state_root

This is also part of #20 #12

**Comment by wubuku** [comment]
One requirement is to get the table item through the key in JSON format.

If JSON RPC can support the serialization of json, is it relatively easy to add deserialization? For example, I plan to emit the key of the table through the event, as mentioned before:

> How to know which keys are in the table. For example, we may need to know which order items (OrderItem) are in the order (Order). The bypass scheme that the example application intends to adopt is: the contract on the application chain emit “Table item added” event... 

If the key in the event got from JSON RPC can be displayed as JSON, then when "Get table item", use this JSON directly. Then “closes the loop ”.

**Comment by jolestar** [comment]
> One requirement is to get the table item through the key in JSON format.
> 
> If JSON RPC can support the serialization of json, is it relatively easy to add deserialization? For example, I plan to emit the key of the table through the event, as mentioned before:
> 
> > How to know which keys are in the table. For example, we may need to know which order items (OrderItem) are in the order (Order). The bypass scheme that the example application intends to adopt is: the contract on the application chain emit “Table item added” event...
> 
> If the key in the event got from JSON RPC can be displayed as JSON, then when "Get table item", use this JSON directly. Then “closes the loop ”.

tracked in #230
