### ISSUE TITLE
[Testing] Move integration test random error and framework tests slow

### ISSUE THREAD

**Issue by jolestar** [rooch-network/rooch#588]
The Move integration test random error and framework tests are slow. We need to figure out why.

<img width="924" alt="Screen Shot 2023-08-08 at 12 25 46" src="https://github.com/rooch-network/rooch/assets/77268/ec441228-15b9-4b4f-ba93-968aa7902ebf">
<img width="902" alt="Screen Shot 2023-08-08 at 12 26 07" src="https://github.com/rooch-network/rooch/assets/77268/4b7acb61-6389-4c2a-a5b3-99df636f21f0">

**Comment by jolestar** [comment]
cc @stevenlaw123

**Comment by stevenlaw123** [comment]
1. On my computer, the testing time for rooch-framework-tests is around 50 seconds, but it takes 300 seconds on our CI checking machine，the performance of the CI checking machine needs to be improved.
2. To display SLOW, you can set the threshold using slow-timeout = "2m".
3. During multiple testing of rooch-framework-tests, there are indeed random `unbound module` errors, and we need to further investigate the cause of this issue.

![2023-08-08_18-46](https://github.com/rooch-network/rooch/assets/141568913/52ae0c51-a3ed-4b14-913c-98843b91f62e)

**Comment by jolestar** [comment]
1. use a single thread for the framework test.
2. the unbound module error should resolved in #724
