### ISSUE TITLE
[session-key] support other schemes for session keys

### ISSUE THREAD

**Issue by feliciss** [rooch-network/rooch#592]
Right now there's only ed25519 scheme supported for session keys. Assuming ed25519 authentication payload as session keys's key map and ed25519 and other schemes' auth keys can be authentication keys in the session key's value map.

I'll add other schemes as feasible to #582.

**Comment by jolestar** [comment]
As #583 discussion, we do not need to support more schemes for SessionKey.

1. More schemes supported, need more tests, increment the complex.
2. Now, we need to find some SessionKey scenarios. If the scenario needs more schemes, we will support it.

@baichuan3 @wow-sven What's your view?
