### ISSUE TITLE
[authentication] `rooch init` command will not rotate an authentication key for the default ed25519 key pair and need manually rotate

### ISSUE THREAD

**Issue by feliciss** [rooch-network/rooch#608]
Update: I saw the `account create` command will send a transaction which will create an authentication key for function `post_execute` if it's not existed. But how about `rooch init` command?

Original post:

Code reference: https://github.com/rooch-network/rooch/pull/602/files#diff-429aa30396a8f8f69d8559b65455ba0cd2012f1d4ad0b741c33c6a52bbdf87cfR95

When calling `rooch account create` or `rooch init`, it would perfectly be automatically rotating an ed25519 authentication key for the ed25519 key pair and address created. If not doing so, users usually will not found themself to rotate the default ed25519 authentication key because the ed25519 key pair will already exist in the local Rooch key store which would be causing confusion for rotating it while the key pair and address already exist, and probably the users will only rotate authentication keys for other schemes by calling `rooch account update`?

Or we should separate `rooch account update` into two commands? `rooch account update` will only be for updating key pairs for schemes in local key store only, and `rooch account rotate` for rotating authentication keys with initiating Rooch RPC transactions for each scheme only.

What do you think? @jolestar

**Comment by jolestar** [comment]
The `rooch init` command is for init a local wallet. 

I think maybe we should make the `rooch account create` to a local command, and not execute a transaction. The account on-chain will auto-create when the account sends the first transaction.

And the first transaction will auto-init the account's ed25519 auth key via `rotate_authencation_key`. Maybe we need to distinguish `init_authencation_key` and `rotate_authencation_key`.

But if we want to attach a new scheme keypair to an account address, the auth key must init first before sending the transaction via the scheme.

cc @wow-sven
