### ISSUE TITLE
[Framework] ecdsa_k1_validator and ecdsa_k1_recoverable_validator

### ISSUE THREAD

**Issue by jolestar** [rooch-network/rooch#613]
@feliciss @wow-sven 

The ecdsa_k1_validator and ecdsa_k1_recoverable_validator are two schemes. We should merge them and keep one.

The goal for ecdsa_k1_validator is to validate the ETH transaction. We support the ETH signature validation scheme.

Another thing is how to test eth transaction supported in Rooch. We should avoid breaking the ETH supported when refactoring the authentication validator.

**Comment by feliciss** [comment]
> The goal for ecdsa_k1_validator is to validate the ETH transaction. We support the ETH signature validation scheme.

So we just merge those two while keeping signature separated? The thing I created two was because ECDSA scheme has two signature lengths, 64-byte length for [r, s] signature and 65-byte for [r, s, v] signature. Ethereum is using 65-byte [r, s, v] signature.

**Comment by jolestar** [comment]
I think we just keep the [r, s, v] version. If we find the use case for [r, s], we can bring it back.

**Comment by feliciss** [comment]
> I think we just keep the [r, s, v] version. If we find the use case for [r, s], we can bring it back.

Mentioning [r, s] signature, there's an article introducing Bitcoin in 2021. Bitcoin was using the [r, s] signature for verification. In Move, we have supported [r, s] signature verification for message, hash function for producing message hash `z`, public key bytes `Q`, and signature bytes [r, s] mentioned in that article. That's how it works for non-recoverable ECDSA signature, if we just keep the recoverable ECDSA signature and recover the public key from the signature, however, the signature bytes would be different for 64-byte non-recoverable signature used in Bitcoin, etc.

**Comment by jolestar** [comment]
So, we can keep the ecdsa_k1 signature verify functions, but it does not need to be an authentication validator scheme. The schnorr may is also like this. 

When integrating Bitcoin transactions, we can design the scheme using ecdsa_k1 and schnorr.

**Comment by jolestar** [comment]
split signature verify function and auth validator function.
