### ISSUE TITLE
[cli] support address mapping when initiating multi-chain transactions to MoveTransactions with command line interface.

### ISSUE THREAD

**Issue by feliciss** [rooch-network/rooch#622]
As discussed in today's meeting. 

1. Address mapping to distinguish transactions from different L1 addresses.
2. Send transactions specific to each blockchain with CLI.

**Comment by jolestar** [comment]
We implement send Ethereum transaction to ETH RPC on rooch first. And I make this TBD.

**Comment by jolestar** [comment]
We directly generate the Bitcoin private key in CLI, and use Bitcoin private key to sign the transaction in #1674
