### ISSUE TITLE
[moveos] Provides a module initialization method

### ISSUE THREAD

**Issue by jolestar** [rooch-network/rooch#63]
When the developer publishes a module, usually needs to call initializer method.

There are some solutions:

1. Starcoin: Provide an init function combined with the modules transaction.

https://github.com/starcoinorg/starcoin/blob/de940468329edb4fbc884e1c2381281c2afd7e49/vm/types/src/transaction/package.rs#L19-L25

```
pub struct Package {
    ///Package's all Module must at same address.
    #[schemars(with = "String")]
    package_address: AccountAddress,
    modules: Vec<Module>,
    init_script: Option<ScriptFunction>,
}
```

2. Sui: Provide a module initializers function spec: https://docs.sui.io/learn/sui-move-diffs#module-initializers

> As described in [Object-centric global storage](https://docs.sui.io/learn/sui-move-diffs#object-centric-global-storage), Sui Move modules are published into Sui storage. A special initializer function optionally defined in a module is executed (once) at the time of module publication by the Sui runtime for the purpose of pre-initializing module-specific data (e.g., creating singleton objects). The initializer function must have the following properties in order to be executed at publication:
> * Name init
> * Single parameter of &mut TxContext type
> * No return values
> * Private

3. Aptos

https://aptos.dev/move/move-on-aptos/modules-on-aptos

> When publishing a module for the first time, The VM will search for and execute an init_module(account: &signer) function.

**Comment by jolestar** [comment]
Option 2

**Comment by baichuan3** [comment]
close via https://github.com/rooch-network/rooch/pull/142
