### ISSUE TITLE
[Example] publish counter example error

### ISSUE THREAD

**Issue by yubing744** [rooch-network/rooch#643]
<img width="997" alt="image" src="https://github.com/rooch-network/rooch/assets/1449069/5533db63-645f-4375-a406-fbec69864fdf">

Steps to reproduce：
1、git clone examples/counter/Move.toml](https://github.com/rooch-network/rooch.git
2、git checkout main
3、cargo build
4、./target/debug/rooch init
5、replace dev-addresses in examples/counter/Move.toml
6、./target/debug/rooch server start
7、./target/debug/rooch move publish -p ./examples/counter/ --sender-account default -d

**Comment by yubing744** [comment]
I created a new project using the rooch move new my_move_project command, wrote a simple counter code, and got the same error when doing a publish.

<img width="970" alt="image" src="https://github.com/rooch-network/rooch/assets/1449069/d5a465ae-27da-4239-8fcb-c2100d3948fa">

**Comment by jolestar** [comment]
thread 'tokio-runtime-worker' panicked at 'pre_execute function should always success: VMError { major_status: VALUE_DESERIALIZATION_ERROR, sub_status: None, message: None, exec_state: None, location: Module(ModuleId { address: 0000000000000000000000000000000000000000000000000000000000000002, name: Identifier("bcs") }), indices: [], offsets: [(FunctionDefinitionIndex(0), 0)] }', moveos/moveos/src/vm/moveos_vm.rs:518:18

**Comment by jolestar** [comment]
I handle this issue.

**Comment by jolestar** [comment]
Just clean the ~/.rooch dir.

**Comment by yubing744** [comment]
> Just clean the ~/.rooch dir.

I tested and deleting the ~/.rooch directory solved this problem for me
