### ISSUE TITLE
[MoveOS] Bug when remove and add value for same table key

### ISSUE THREAD

**Issue by pause125** [rooch-network/rooch#648]
When [publish_modules](https://github.com/rooch-network/rooch/blob/e619c845f9b532430c65858ba2e0d2ff1c4b9e86/moveos/moveos-stdlib/moveos-stdlib/sources/account_storage.move#L171C24-L171C24) in Move, if the module exists in table, we `remove` old module first and then `add` new one which will create `Op::New` and `Op::Delete` respectively when converting table data into `StateChangeSet`.

But the `StateChangeSet` can only store only one `Op` for a key of a table, so one of `Op` above will be covered when finish the transaction. The upgrading will **fail** without any transaction error.

**Comment by jolestar** [comment]
Remove + Add = Update. We need a test case to figure it out.
