### ISSUE TITLE
[Framework] genesis module

### ISSUE THREAD

**Issue by baichuan3** [rooch-network/rooch#67]
when the chain starts, initialize the genesis account, timestamp, chain config, gas, version and other information

**Comment by jolestar** [comment]
Genesis build or Genesis init? Maybe dependent on #63

**Comment by jolestar** [comment]
Is this issue finished? How to define this issue's requirement? @baichuan3

**Comment by baichuan3** [comment]
Some framework initialization is completed by the module init function. At this stage, the genesis contract only needs to initialize the genesis account and timestamp. Subsequent initialization including chain configuration, gas, version, etc. will be completed in genesis in next milestones.

It will be easier to implement, I will submit a pr this week.

**Comment by jolestar** [comment]
@baichuan3 I put this to the v0.2 milestone. The description of this issue needs to be improved.

**Comment by jolestar** [comment]
Close this issue. The features can be split into other issues.
