### ISSUE TITLE
[rooch-types] define currency symbol binding chain ID

### ISSUE THREAD

**Issue by feliciss** [rooch-network/rooch#691]
When adding a custom network on MetaMask, it is needed to add a currency symbol:

> Ticker symbol verification data is currently unavailable, make sure that the symbol you have entered is correct. It will impact the conversion rates that you see for this network.

Relative issue #690

**Comment by jolestar** [comment]
part of #604

**Comment by jolestar** [comment]
The default symbol is `GasCoin`.

**Comment by jolestar** [comment]
The symbol is RGC, RoochGasCoin. https://github.com/rooch-network/rooch/blob/5eda9480ff744a4e50e62879056753054b8f40eb/crates/rooch-framework/sources/gas_coin.move
