### ISSUE TITLE
[Cli] Cli config & Keystore support multi env, including devnet/testnet/mainnet

### ISSUE THREAD

**Issue by baichuan3** [rooch-network/rooch#697]

**Comment by jolestar** [comment]
Is this finished? relative #755

**Comment by baichuan3** [comment]
Not yet.

As part of https://github.com/rooch-network/rooch/issues/755, Share the keystore file between different network, Cli config need to support different network.

**Comment by jolestar** [comment]
The cli config already supports multi-Env. The env is for different networks.

**Comment by baichuan3** [comment]
Then this PR is completed and can be closed.
