### ISSUE TITLE
[TBD] Disable publish modules through MoveAction::ModuleBundle?

### ISSUE THREAD

**Issue by pause125** [rooch-network/rooch#703]
Currently, developers have two options to publish modules:

1. Request [MoveAction::ModuleBundle](https://github.com/rooch-network/rooch/blob/23ebddb7155979da5cc05b4b74a96253609d01fa/crates/rooch/src/commands/move_cli/commands/publish.rs#L153C60-L153C60).
1. Invoking Contract [moveos_std::account_storage::publish_modules](https://github.com/rooch-network/rooch/blob/23ebddb7155979da5cc05b4b74a96253609d01fa/moveos/moveos-stdlib/moveos-stdlib/sources/account_storage.move#L178).

With the second approach, developers can customize the upgrade strategy of contracts flexibly.  Is there still a need to retain the first approach?

**Comment by jolestar** [comment]
The genesis transaction needs the first approach, maybe we only allow the genesis transaction to use MoveBundle?

**Comment by jolestar** [comment]
We can make the cli `move publish` command's `--by-move` option default to true first.

**Comment by jolestar** [comment]
We only allow the genesis tx publish modules through MoveAction::ModuleBundle
