### ISSUE TITLE
[Framework] Store Move packages meta on-chain

### ISSUE THREAD

**Issue by pause125** [rooch-network/rooch#704]
There may have some meta infomations of Move packages to be stored on-chain. 

For example, the upgrading policy. There are two basic policies:  **compatible**, **immutable**. We need to store the configurations on-chain and check every time publish modules.

**Comment by jolestar** [comment]
Should we also store the source on-chain?

**Comment by jolestar** [comment]
Add struct field will break the compatibility.

Add PackageMetadata to the Package's dynamic field?

Keep all modules in PackageMetada is not a good idea. We can continue to keep the modules as package dynamic fields.

**Comment by jolestar** [comment]
The source code can use the `module_name.move` as the key of the dynamic field.
