### ISSUE TITLE
CLI private key and account profile

### ISSUE THREAD

**Issue by jolestar** [rooch-network/rooch#71]

**Comment by jolestar** [comment]
Do you mean to maintain the account in a local config file? I think it is ok.

But do we allow cli to read the account config files directly? or the cli needs to connect to a local server to read the account.

**Comment by wow-sven** [comment]
> Do you mean to maintain the account in a local config file? I think it is ok.
> 
> But do we allow cli to read the account config files directly? or the cli needs to connect to a local server to read the account.

Yes, the cli can directly manipulate the configuration file, and later we can encrypt the configuration file

**Comment by jolestar** [comment]
But if we encrypt the file, use need to decrypt the file every time. The server side can hold the decrypted result in memory, but cli can not.

starcoin supports this approach, but the starcoin cli is an interactive console that runs as a long time progress.

**Comment by jolestar** [comment]
CLI's primary account feature is implemented.
