### ISSUE TITLE
[transaction-validator] ErrorValidateBadChainId resulted from calling MetaMask counter web example

### ISSUE THREAD

**Issue by feliciss** [rooch-network/rooch#722]
When running the counter web example, it needs to be updated for Chain ID in transaction validator.

```zsh
[debug] 20230102
[debug] 20230103
```

The default chain id is `20230102` by starting the rooch server. However, the `rooch init` command inits a profile of chain id `20230103`.

This causes incongruous chain id for transaction validator to validate, and resulted below errors:

```zsh
WARN connection{remote_addr=127.0.0.1:62978 conn_id=0}: rooch_executor::actor::executor: transaction validate vm error, tx_hash: 0x57b2…a442, error:MoveAbort { location: 0000000000000000000000000000000000000000000000000000000000000003::transaction_validator, category_code: 1, reason_code: 1006 } 
```

```zsh
rooch move explain -l 0000000000000000000000000000000000000000000000000000000000000003::transaction_validator -a 1006
Category Code: 0
Category Name: Unknown
Reason Code: 1006
Reason Name: ErrorValidateBadChainId
Code Description: 

Success
```

**Comment by feliciss** [comment]
Shall we use `20230102` or `20230103 ` as the default chain id? @jolestar @baichuan3

**Comment by baichuan3** [comment]
currently test chain id as default, change to dev change id ? @jolestar

**Comment by jolestar** [comment]
Yes, make the dev default, and we can change it after the test network is ready.
