### ISSUE TITLE
[CLI] Make cli stable

### ISSUE THREAD

**Issue by jolestar** [rooch-network/rooch#755]
To make cli stable, we must ensure compatibility as much as possible.

- [x] To make cli config stable
- [x] To make the keystore stable
- [x] Share the keystore file between different network
- [x] #854
- [x] #855
- [x] #932
- [x] #933 

Encrypting keystore files can affect the developer experience and existing test cases. There are several options to consider:

1. Do not encrypt the keystore file if the user does not provide a password at the `init` command, and then record whether or not it is encrypted in the keystore file.
2. Default the password to an empty string and decrypt it with the empty string if the user does not enter it.

@feliciss @wow-sven @baichuan3

**Comment by feliciss** [comment]
2 seems to be a bad choice.

**Comment by feliciss** [comment]
>  Encrypt the private key in the keystore file

What's the case for encrypting the private key? As I know the keys in key store file are actually key pair bytes.

> Provide a password option for the cli commands

I think the password can be used to generate a seed below:

```rs
let seed = Seed::new(&mnemonic, password_str);
```

As you mentioned in 2, the default seed phrase is empty string "", and we can use the input password as the seed phrase password and use the seed phrase to generate a nonce and a encryption key to encrypt the key pairs.

Ref: #856

**Comment by jolestar** [comment]
we just encrypted the private key in keystore file, not the file.

**Comment by baichuan3** [comment]
discussion:
1. Mark whether the keystore is encrypted and supports single password encryption. If it is not encrypted, you will not be prompted to enter a password.
2,
3. Only supports a single mnemonic word, removes import, and supports passing in the mnemonic word recovery address during rooch init.
