### ISSUE TITLE
[rooch-rpc-server] merge `get_transaction_by_index` and `get_transaction_by_hash` into `get_transaction_by_hash_and_index`

### ISSUE THREAD

**Issue by feliciss** [rooch-network/rooch#757]
At the time of writing, rooch is using separate `get_transaction_by_index` and `get_transaction_by_hash` for `rooch-rpc-server` and `rooch-sequencer`, which is different from implementations from `ethers-rs` library: https://docs.rs/ethers/latest/ethers/?search=get_transaction_by_block

When searching the keyword `get_transaction_by_block`, there's only an implementation of `get_transaction_by_block_and_index`.

In compliance with the de-facto official implementation, I think we should merge above two into one function `get_transaction_by_hash_and_index`.

The second params index should be `u64`, not counting start and end index.

Current implementation: https://github.com/rooch-network/rooch/blob/948596c33b9bd4d8b57c8ab077512c08679c1900/crates/rooch-rpc-server/src/server/eth_server.rs#L310

**Comment by feliciss** [comment]
After merge, we can change `get_transaction_by_index` to `get_transaction_by_indices` with a range.

**Comment by feliciss** [comment]
Extend `get_transaction_by_hash` to `get_transaction_by_hash_and_index` by resolving in commit https://github.com/rooch-network/rooch/pull/735/commits/38aa577e6a80264eceba66f76f9c563cb8ca3530

**Comment by baichuan3** [comment]
How to close this issue? 

Currently Rooch has three types of transaction API implements,  and the transaction API need to be refactor according to the requirements displayed on the Dashboard.

**Comment by feliciss** [comment]
> How to close this issue?
> 
> Currently Rooch has three types of transaction API implements, and the transaction API need to be refactor according to the requirements displayed on the Dashboard.

The issue has already been closed.

I don't know much about the Dashboard thing. Can you explain in more details?
