### ISSUE TITLE
[Document] Setup MetaMask

### ISSUE THREAD

**Issue by jolestar** [rooch-network/rooch#773]
- [x] Install MetaMask
- [x] Config the RPC for MetaMask(dev network and test network)
- [x] Provide one-click link to add the network

**Comment by wow-sven** [comment]
dashboard can automatically add networks

**Comment by wow-sven** [comment]
This aa can be turned off 
1. rooch doc https://rooch.network/docs/user-guides/interact-with-metamask
2. dashboard auto config
