### ISSUE TITLE
how to locate and resolve `MiscellaneousError`

### ISSUE THREAD

**Issue by geometryolife** [rooch-network/rooch#775]
## Repetition

When I try to publish the `simple_blog` example, it will appear `Transaction error: Transaction execution failed: MiscellaneousError`

```shell
$ rooch move publish --named-addresses simple_blog=default

INCLUDING DEPENDENCY MoveStdlib
INCLUDING DEPENDENCY MoveosStdlib
INCLUDING DEPENDENCY RoochFramework
BUILDING simple_blog
Publish modules to address: 0xf5ecfc49f55e283119104978b60995b0ec84a5bd760a0305b24b9a4175deff7b
Transaction error: Transaction execution failed: MiscellaneousError
```

**rooch server logs**:

```shell
2023-09-10T16:26:18.373266Z  WARN connection{remote_addr=127.0.0.1:36882 conn_id=0}: moveos::moveos: execute tx(0xe5f7…d1bf) error: Err(VMError { major_status: LINKER_ERROR, sub_status: None, message: Some("Cannot find ModuleId { address: f5ecfc49f55e283119104978b60995b0ec84a5bd760a0305b24b9a4175deff7b, name: Identifier(\"article\") } in data cache"), exec_state: None, location: Module(ModuleId { address: 0000000000000000000000000000000000000000000000000000000000000002, name: Identifier("move_module") }), indices: [], offsets: [(FunctionDefinitionIndex(7), 0)] })
```
I want to know how to solve it.

## Steps

- commit hash 900bb11433b76b7f0e78bf363ddb5a510da6fb54
- `cargo build`
- change directory to `simple_blog` and then execute the `rooch move build --named-addresses simple_blog=default`
- `rooch move publish --named-addresses simple_blog=default`
- **Output**:
```
[joe@mx simple_blog]$ rooch move build --named-addresses simple_blog=default
INCLUDING DEPENDENCY MoveStdlib
INCLUDING DEPENDENCY MoveosStdlib
INCLUDING DEPENDENCY RoochFramework
BUILDING simple_blog
Success
[joe@mx simple_blog]$ rooch move publish --named-addresses simple_blog=default
INCLUDING DEPENDENCY MoveStdlib
INCLUDING DEPENDENCY MoveosStdlib
INCLUDING DEPENDENCY RoochFramework
BUILDING simple_blog
Publish modules to address: 0xf5ecfc49f55e283119104978b60995b0ec84a5bd760a0305b24b9a4175deff7b
Transaction error: Transaction execution failed: MiscellaneousError
```

**Comment by jolestar** [comment]
Clear the local data and try again.

**Comment by geometryolife** [comment]
> Clear the local data and try again.

It doesn't work, I have already tried to `rooch server clean`, and even re-executing `rooch init` to generate a new configuration is the same.

**Comment by jolestar** [comment]
Seam like it is a bug. The simple_blog can publish via `--by-move-action`, but can not publish via move contract.  @pause125

**Comment by geometryolife** [comment]
> @geometryolife I'm sorry, but I cannot reproduce the issue you are experiencing. I can successfully deploy the simple_blog contract without any issues. If you have any detailed reproducable steps that might help me understand the problem better, please share them with me.

Alright, I have supplied the Steps for recurring the bug.

**Comment by geometryolife** [comment]
> how do you start server, and could you please paste the server logs?

Already provided available.

Here is screenshot:
![image](https://github.com/rooch-network/rooch/assets/54882546/e9117e71-7365-40e3-a98f-4d610f77fff4)
