### ISSUE TITLE
Rooch TOC of docments

### ISSUE THREAD

**Issue by geometryolife** [rooch-network/rooch#776]
- Basic concepts
  - About Rooch
    - Rooch key glossary
    - Why Move
    - Diifer from other L2
    - Rooch name addresses (0x1/0x2/0x3)
  - How Rooch works
    - object
    - object storage
    - storage context
    - account storage
    - interactive with Ethereum
  - Rooch Tech highlight
    - ...
- Rooch usage
  - installation
  - start rooch server
  - connect to Rooch network
    - local network
    - dev network
    - test network
    - main network
  - Rooch faucet
  - Interactive with MetaMask
  - Create Rooch Move contact
    - some Move basic concepts
    - ...
  - Publish to rooch network
  - Dashboard
  - Rooch RPC
  - Explore
  - examples docments
- Rooch build
  - how to contribute to Rooch
  - Rooch's code conventions
  - ...

**Comment by geometryolife** [comment]
If you have any suggestions for the TOC documents, please modify the above TOC **directly**.

**Comment by jolestar** [comment]
We can improve documents based on the current version.

> To general users

* Introduction
* Rooch
* Rooch Network
* Rooch Tech highlight
  * ... 

> To developers

* Basic concepts
* Rooch usage
* Build DApp on Rooch
* How Rooch works

> To contributors

* How to contribute to Rooch
