### ISSUE TITLE
[Multichain] Introduce a L1ToL2 transaction type

### ISSUE THREAD

**Issue by jolestar** [rooch-network/rooch#779]
Based on the #731 L1ToL2 message solution, we need to introduce a new L1ToL2 transaction type.

In the beginning, I wanted to handle the L1ToL2 message via the contract, but if we want to support arbitrary transactions from L1(force inclusion), we need to support call MoveAction in Move #486. However, there are some security issues to support dynamic invocation.

So, introducing a specific transaction type for the L1ToL2 transaction is a simpler solution.

From 

```rust
pub struct RoochTransactionData {
    /// Sender's address.
    pub sender: RoochAddress,
    // Sequence number of this transaction corresponding to sender's account.
    pub sequence_number: u64,
    // The ChainID of the transaction.
    pub chain_id: u64,
    // The max gas to be used.
    pub max_gas_amount: u64,
    // The MoveAction to execute.
    pub action: MoveAction,
}
```

To

```rust
pub struct RoochTransactionData {
    //....
    pub payload: TransactionPayload,
}
```

```rust
pub enum TransactionPayload{
   Action(MoveAction),
   L1BlockHeader(L1BlockHeader),
   L1ToL2Message(L1ToL2Message),
}
```

```rust
pub struct L1BlockHeader{
  pub coin_id: u64, // distinguish different chains, defined in MultiChainAddress, maybe need a better name?
  pub header: Vec<u8>,
}
```

```rust
pub struct L1ToL2Message{
  pub coin_id: u64, 
  pub inclusion_proof: Vec<u8>, // proof the message is included in a block header.
  pub codec_type: u8, // BCS, RLP, or ..
  pub message: Vec<u8>, // decode to L1EventMessage via codec type and coin_id
}
```

```rust
pub struct EVML1EventMessage{
  pub sender: EVMAddress,
  pub max_gas_amount: u64,
  pub action: MoveAction,
}

When TransactionPayload::L1ToL2Message, the `sender` in `RoochTransactionData` is relayer's address, and the `sender` in `EVML1EventMessage` is the real user to execute the MoveAction.

But we also need to validate the `EVML1EventMessage` before executing it, and the validated result also needs to be recorded in the `TransactionExecutionInfo`.

**Comment by emptinesssubodhi** [comment]
For force inclusion:

1. only messages from arbitration chain can be arbitrated
2. user generate proof off-chain then call abitration contract on L1 (L1 could check this proof), after verification, L2 have to give the inclusion proof within a fixed time window

@jolestar

**Comment by jolestar** [comment]
It seems like we do not need to introduce a new transaction type. We just need to design a new authentication validator, the validator's authenticator is the inclusion_proof.

**Comment by emptinesssubodhi** [comment]
> It seems like we do not need to introduce a new transaction type. We just need to design a new authentication validator, the validator's authenticator is the inclusion_proof.

@jolestar except inclusion_proof, it should check the MoveAction include needed functions for messaging and checks

**Comment by jolestar** [comment]
Finished, we introduce `LedgerTxData`

```
pub enum LedgerTxData {
    L1Block(L1Block),
    L1Tx(L1Transaction),
    L2Tx(RoochTransaction),
}
```
