### ISSUE TITLE
[MoveVM] Binding module address when module publishing

### ISSUE THREAD

**Issue by jolestar** [rooch-network/rooch#781]
Binding module address when module publishing.

Suppose we want to deploy a prepared bytecode module, like a CoinType module, to a user or resource account within the Move contract. In that case, it is not feasible because the address in the module does not match the user's address.

So, we need to find a solution to change the module address when publishing the module.

1. Remapping module address to another address, like https://github.com/aptos-labs/aptos-core/issues/8379
2. Use a fixed placeholder address, like `0xB1ACE40DE2`; if the module address is the placeholder address, do not check the module address with the current sender's address; directly replace the module address with the sender's address.

**Comment by WGB5445** [comment]
This is a good question, I was wondering if we could try to separate the code from the address, the code does not contain the current address information, when deployed after registering the module on the address , the code can be deployed to any address

**Comment by jolestar** [comment]
The address is in the module's AddressIdentifierPool, but we can replace the address when publishing. Now, we need to find a good approach to do this.
