### ISSUE TITLE
[multichain-ids] build custom chain ids to separate from built-in chain ids

### ISSUE THREAD

**Issue by feliciss** [rooch-network/rooch#791]
Discussion:

https://github.com/rooch-network/rooch/pull/787#discussion_r1322428906
https://discord.com/channels/1078938449974935592/1151268013169979486

Build custom chain ids for each blockchain to substitute `coin_id` and separate from built-in Rooch chain ids.

I think we can remove `CoinID` from `coin_type.rs` and build from CustomChainID here:

https://github.com/rooch-network/rooch/blob/9ebd7c3b1ba61fcc83ce278ae92118f2fb97e580/crates/rooch-types/src/chain_id.rs#L197-L210

**Comment by jolestar** [comment]
### multichain_id

Every chain, including the rooch, has a unique ID in rooch. We define it or follow the https://github.com/satoshilabs/slips/blob/master/slip-0044.md. This id is to distinguish different chains when implementing multichain settlement.

The first use case is the MultichainAddress.

### chain_id: 

Follow the ETH chain id. Rooch's dev/test/main network has a different chain_id. 

```rust
pub const CHAIN_ID_DEV: u64 = 20230103;
pub const CHAIN_ID_TEST: u64 = 20230102;
pub const CHAIN_ID_MAIN: u64 = 20230101;
```

### Authenticator scheme id

Every Authentication validator contract has a scheme ID. Assign the ID when the validator registers in the auth_validator_registry.

Currently support:

1. Rooch Native authentication validator: ed25519 signature.
2. Ethereum authentication validator: ethereum ecdsa k1 recoverable signature.

In the future, we can support:

1. zklogin authentication validator.
2. https://github.com/rooch-network/rooch/issues/467


Although the Authenticator scheme ID is sometimes repeated with multichain_id, the two have different use scenarios.
