### ISSUE TITLE
Refactor the keypair management of sequencer, proposer, and relayer

### ISSUE THREAD

**Issue by jolestar** [rooch-network/rooch#800]
Refactor the keypair management of sequencer, proposer, and relayer.

Currently, we auto-generate a keypair to the sequencer, proposer, and relayer. We need to ensure the keypair of the server is stable.

1. Add the keypair config in the server config.
2. Use rooch cli keystore on the server side.

### Refs
1. #755

**Comment by bytedeveloperr** [comment]
I want to work on this

**Comment by jolestar** [comment]
@baichuan3, are you working on this?

**Comment by baichuan3** [comment]
> @baichuan3, are you working on this?

yes

**Comment by bytedeveloperr** [comment]
Oh, alright then 👍
