### ISSUE TITLE
[MoveOS] Publish modules in Move

### ISSUE THREAD

**Issue by jolestar** [rooch-network/rooch#83]
The AccountStorage provides a function to publish modules in Move

```move
public fun publish_modules(ctx: &mut StorageContext, account: &signer, modules: vector<vector<u8>>);
```

The function is incomplete, and MoveOS need to provide some native function:

1. Get the module name in Move by the module bytecode.
2. Verify the modules.
3. Check the module's compatibility.

**Comment by pause125** [comment]
What upgrade policies are Rooch going to support?

**Comment by jolestar** [comment]
TBD, any idea?

**Comment by pause125** [comment]
The basic three policies: `arbitrary`, `compatible`, `immutable` are essential.  

The two-phase upgrade policy in Starcoin is also a good approach, but coupling it with the DAO system makes it somewhat cumbersome and inflexible.   

We can simplify it as follows: In the first phase, developers submit the binary file of a package and receive a capability that can only be stored. In the second phase, the package is actually submitted to the blockchain using the capability, completing the upgrade. In between these two phases, developers can customize a contract to determine when it's appropriate to trigger the second phase. Our framework can also provide some basic management contracts.

**Comment by jolestar** [comment]
We may not support `arbitrary` upgrades, at least we need to ensure compatibility.

**Comment by pause125** [comment]
I'd like to try this issue. Before we start, we can discuss it in the next community meeting.
