### ISSUE TITLE
Serialization for multi-chain

### ISSUE THREAD

**Issue by popcnt1** [rooch-network/rooch#835]
background:

To satisfy the arbitration needs of transaction（L1 to L2 Messaging) inclusion, we need a uniform serialisation scheme for the l1 l2 arbitration chain

approach:

1. implement bcs in solidty
> pros: direct
> cons: complex contracts

2. rooch_node converts solidity abi -> bcs
> pros: no need to implement bcs in solidty
> cons: Care needs to be taken to implement a verifiable mechanism to prove that transactions running on the rooch are consistent with non-bcs encoded actions, either through a verfier challenge or a direct determination in the arbitration chain.

**Comment by popcnt-subodhi** [comment]
Approach 2 is preferred:

The process of converting the serialization can be reproduced on the every executor, so it could be caught by interactive proof.
