### ISSUE TITLE
Data Availability raw KV Interface

### ISSUE THREAD

**Issue by steelgeek091** [rooch-network/rooch#85]
**1. Store message to DA Server.**

**URL:**
```txt
/v1/da/message/store
```

**Method:**

```
POST
```

**Request:**

```rust
struct Request {
	message: Vec<u8>,
	timeout: u64,
	signature: Vec<u8>
}
```

**Response:**

```rust
struct Response {
	KeysetHash: Vec<u8>,
	DataHash:	Vec<u8>,
	Timeout: u64,
	SignersMask: u64,
	Sig: Vec<u8>,
	Version: u8,
}
```

**2. Get message from DA Server.**
**URL:**
```txt
/v1/da/message/get
```

**Method:**

```
POST
```

**Request:**

```rust
struct Request {
	hash: Vec<u8>
}
```

**Response:**

```rust
struct Response {
	data: Vec<u8>
}
```

**3. Check health status for DA Server.**

**URL:**
```txt
/v1/da/status/get
```

**Method:**

```
GET
```

**Response:**

```rust
HTTP Status
503 means StatusServiceUnavailable
200 means StatusOK
```

**4. Get expiration policy from DA Server.**

**URL:**
```txt
/v1/da/expiration_policy/get
```

**Method:**

```
GET
```

**Response:**

```rust
KeepForever	// Data is kept forever
DiscardAfterArchiveTimeout	// Data is kept till Archive timeout
DiscardAfterDataTimeout // Data is kept till aggregator provided timeout
MixedTimeout	// Used for cases with mixed type of timeout policy
DiscardImmediately // Data is never stored
```

**Comment by templexxx** [comment]
1. for api name in path: message -> kv, means these api are for raw kv, they are basic interface
2. store -> put
3. for store, message -> value (in struct)
4. need better name for keyset (easier to understand) & signermask too
5. for get, could put hash as URL's param (with url safe base64 encode), http get method is eaiser to use
6. status: no need get in path
7. no expiration policy in this stage. Need further disscution, Im thinking about the put policy, not just expiration

@steelgeek091

**Comment by templexxx** [comment]
@steelgeek091 breif explaination here is better
