### ISSUE TITLE
[bug] couldn't fetch chain id from a remote RPC URL address with MetaMask even switched to the env

### ISSUE THREAD

**Issue by feliciss** [rooch-network/rooch#851]
### Using `0.0.0.0` port:

![Screenshot 2023-09-21 at 20 09 28 cleaned](https://github.com/rooch-network/rooch/assets/22887031/6956fba4-0cda-4236-9e0b-c0840926bd87)

### Using a remote RPC port:

![Screenshot 2023-09-21 at 20 09 51 cleaned](https://github.com/rooch-network/rooch/assets/22887031/82a2b3bc-f1fa-4744-858f-f2ab899c5363)

Even switched to `active_env: test` didn't work:

```zsh
envs:
- chain_id: 20230103
  alias: default
  rpc: http://0.0.0.0:50051
  ws: null
- chain_id: 20230102
  alias: test
  rpc: https://seed-testnet.rooch.network/
  ws: null
active_env: test
```

**Comment by yourmoonlight** [comment]
the rpc url had been changed to https://dev-seed.rooch.network/

**Comment by feliciss** [comment]
> the rpc url had been changed to https://dev-seed.rooch.network/

It works.
