### ISSUE TITLE
[bug] Session Key's time is incorrect

### ISSUE THREAD

**Issue by jolestar** [rooch-network/rooch#896]
<img width="1491" alt="Screen Shot 2023-09-30 at 22 27 50" src="https://github.com/rooch-network/rooch/assets/77268/1df8b83c-c60d-4719-8725-d210cabdfeb0">

The timestamp is right.

```bash
rooch state -a /resource/0x3/0x3::timestamp::CurrentTimeMicroseconds
```
```json
[
  {
    "state": {
      "value": "0x00e0e50195060600",
      "value_type": "0x3::timestamp::CurrentTimeMicroseconds"
    },
    "move_value": {
      "abilities": 8,
      "type": "0x3::timestamp::CurrentTimeMicroseconds",
      "value": {
        "microseconds": "1696086912000000"
      }
    }
  }
]
```

**Comment by yubing744** [comment]
@jolestar I ran a node locally and the timestamp obtained was always 0

![image](https://github.com/rooch-network/rooch/assets/1449069/dee318e3-2e63-4c7b-abff-ce39db10a570)

**Comment by jolestar** [comment]
@yubing744

Start the local node with relayer: #790 

```bash
rooch server start -n local --eth-rpc-url https://goerli.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161
```

Or call `0x3::timestamp::fast_forward_seconds_for_local`

**Comment by yubing744** [comment]
> node

OK
