### ISSUE TITLE
[statedb] Implement a node storage for StateDB

### ISSUE THREAD

**Issue by jolestar** [rooch-network/rooch#9]
Currently, the node storage only implements an InMemoryStore. We need to provide a simple disk store first.

1. Introduce an embedded database, such as Rocksdb.
Or 2. Just using the file system to store the state tree's nodes. 

TBD

1. Should we split the SMT's leaf value from the node?

**Comment by feliciss** [comment]
> 1. Introduce an embedded database, such as Rocksdb.

Better to look at https://github.com/holepunchto/hypercore?

Its Rust implementation: https://github.com/datrs/hypercore.

**Comment by jolestar** [comment]
> > 1. Introduce an embedded database, such as Rocksdb.
> 
> Better to look for at https://github.com/holepunchto/hypercore?
> 
> Its Rust implementation: https://github.com/datrs/hypercore.

Has Hyperbee sufficient maturity?

**Comment by feliciss** [comment]
> > > 1. Introduce an embedded database, such as Rocksdb.
> > 
> > 
> > Better to look for at https://github.com/holepunchto/hypercore?
> > Its Rust implementation: https://github.com/datrs/hypercore.
> 
> Has Hyperbee sufficient maturity?

No. I think it's a quite new p2p technology that emerged in 2020, mentioning its original research: https://github.com/hypercore-protocol/p2p-indexing-and-search.

There needs to be more precautious attentions to this tech. I recommend these readings:

1. https://gist.github.com/RangerMauve/ae271204054b62d9a649d70b7d218191
2. https://blog.hyper.io/p2p-databases-hyperbee/

Hyperbee is based on JavaScript, and from my research, there isn't a library for Rust yet.

**Comment by baichuan3** [comment]
close as completed via https://github.com/rooch-network/rooch/pull/454 and https://github.com/rooch-network/rooch/pull/523
