### ISSUE TITLE
[bug] MetaMask cannot decode the status and transaction data for Chain ID 20230104 for local

### ISSUE THREAD

**Issue by feliciss** [rooch-network/rooch#904]
When connecting with local network in `rooch.yaml` with MetaMask and send a transaction, it cannot be decoded for the transaction data and the status is `failed`.

It may need to be fixed ASAP.

**Comment by yubing744** [comment]
How to reproduce? Are you operating in Dashboard?

**Comment by feliciss** [comment]
> How to reproduce? Are you operating in Dashboard?

No. I used MetaMask on Firefox extension, not using Dashboard.

**Comment by jolestar** [comment]
How do you send the transaction and what does the transaction do? You can find the transaction detail info in the log.

**Comment by jolestar** [comment]
Is this issue resolved?

**Comment by feliciss** [comment]
> Is this issue resolved?

It seems that counter web example had been removed from main branch. For this reason, I could not retest the verification logic using MetaMask.

**Comment by feliciss** [comment]
It has been worked out for the new counter example and there's no error with the rooch server.
