### ISSUE TITLE
[Framework] Check module dependency order when publish

### ISSUE THREAD

**Issue by pause125** [rooch-network/rooch#928]
When publishing modules through `moveos_stdlib::account_storage::publish_modules_entry(ctx: &mut Context, account: &signer, modules: vector<vector<u8>>)`, the input parameter `modules` may not be sorted in dependency order which will cause `MiscellaneousError` for developers.  A previous issue #775.

We can optimize developer experience through the following options:

- Option 1: Check the order when verify modules, abort with meaning code if modules not sorted by dependency order.
- Option 2: Auto sort modules by dependency order when verify modules.

**Comment by jolestar** [comment]
Prefer Option2
