### ISSUE TITLE
[cli] rooch server clean not work

### ISSUE THREAD

**Issue by yourmoonlight** [rooch-network/rooch#937]
rooch server clean -d ~/.rooch/
StoreConfig init store dir "/root/.rooch/local/roochdb/rooch_store" "/root/.rooch/local/roochdb/moveos_store"
Rooch server storage successfully cleaned

du -sh ~/.rooch/
615M	/root/.rooch/

**Comment by baichuan3** [comment]
`Rooch server clean`, by default cleans the db data of the `local` network. 
If it is another network (dev), need to specify the network. example:
`rooch server clean -n dev`

**Comment by yourmoonlight** [comment]
> `Rooch server clean`, by default cleans the db data of the `local` network. If it is another network (dev), need to specify the network. example: `rooch server clean -n dev`

Thanks. 
Confirmed, I will close this issue
