### ISSUE TITLE
[validator-test] providing a function to convert Rooch address and transaction into Ethereum address & tx. 

### ISSUE THREAD

**Issue by feliciss** [rooch-network/rooch#945]
Related PR #942.

**Comment by jolestar** [comment]
We can directly use ether.rs to generate Ethereum transactions, just put the MoveAction bcs bytes as the ethereum transaction's call data.

**Comment by feliciss** [comment]
> We can directly use ether.rs to generate Ethereum transactions, just put the MoveAction bcs bytes as the ethereum transaction's call data.

Could you give me some examples? I don't know how to convert from ether's `Transaction` type to Rooch's `RoochTransactionData` and sign it to construct a `MoveOSTransaction` using the Rooch's address as a resolver to be passed into ethereum validator.

**Comment by jolestar** [comment]
1. Construct an `EthereumTransactionData(ethers::types::Transaction)`. ps: the EthereumTransactionData should be renamed EthereumTransaction
2. EthereumTransactionData::construct_moveos_transaction => MoveOSTransaction

https://github.com/rooch-network/rooch/blob/612856039dcc28867ae1a218852615da54dd5885/crates/rooch-executor/src/actor/executor.rs#L126-L134
