### ISSUE TITLE
Is it possible for the default local database storage of MoveOS to provide master-slave replication functionality?

### ISSUE THREAD

**Issue by wubuku** [rooch-network/rooch#96]
MoveOS, as a standalone Move runtime environment, has one of its design features as follows:

* State storage and retrieval: it provides a default local database storage, which can be customized by applications.

My question is whether it is possible for the default database storage itself to provide master-slave replication functionality?

In traditional Web2 applications, when the number of users increases and performance needs to be improved, the first tool used is often to implement read-write access separation through the master-slave replication mechanism of the database. For features that are not too sensitive to data consistency (master-slave replication lag), all data is read from the slave database.

If there is a master-slave replication of the database, it is easier to build a Node API service that provides read-only (query) features on top of it. (Then on this basis, it can be combined with Service Mesh for traffic management...)

**Comment by jolestar** [comment]
Providing database storage, like Mysql storage?

**Comment by wubuku** [comment]
I saw that design feature in the MoveOS documentation. What I find interesting is how customizable the state storage can be and I wonder to what extent it can be achieved.

For example, is it possible for an application chain to directly use a mature database like MySQL to store chain data? This way, existing features of MySQL such as master-slave replication mechanism can be fully utilized.

Of course, as an event sourcing system, the blockchain can achieve data replication by synchronizing transaction data through P2P networks. However, there may also be advantages to doing this at the database level. For example, more powerful tools can come into play. We know that many database tools that support data sharding (like Apache ShardingSphere) are also compatible with the MySQL client protocol.

**Comment by jolestar** [comment]
The storage API is a KeyValue API.

https://github.com/rooch-network/rooch/blob/40ac3ff2945342ec325181cd42113724f9007022/moveos/smt/src/lib.rs#L29-L34

The key is Hash, and the Value is SMT node binary. 

I do not figure out if we should let the storage know the node type.

If the storage knows the Node type, if the node is a leaf node, and it is a Move Object<T> binary and got the T's Move Layout, the storage can map the Object field to the database record.

**Comment by jolestar** [comment]
We need to sync the state via Rooch API and do not need the database-level replication.
