### ISSUE TITLE
[Document] Update document to talk about `examples` project named rules

### ISSUE THREAD

**Issue by geometryolife** [rooch-network/rooch#967]
这里写个固定的地址，会导致 example 自动发布失败。另外 ci 中 example 的 named_address 是自动根据 project 目录来设置的。比如这个 project 的 name_address 就是 `quick-start`。 如果 `quick-start` 作为 named_address 不合法，就需要改成 `quick_start`

_Originally posted by @jolestar in https://github.com/rooch-network/rooch/pull/952#discussion_r1358085553_

**Comment by jolestar** [comment]
This should be part of the example documents, not an article.

**Comment by jolestar** [comment]
part of example-guides https://rooch.network/docs/example-guides https://rooch.network/zh-CN/docs/example-guides
