### ISSUE TITLE
[Review]  Event RPC

### ISSUE THREAD

**Issue by jolestar** [rooch-network/rooch#969]
Part of #966 

```
#[derive(Debug, Clone)]
pub struct AnnotatedMoveOSEvent {
    pub event: Event,
    pub sender: AccountAddress,
    pub tx_hash: Option<H256>,
    // pub event_data: Vec<u8>,
    pub timestamp_ms: Option<u64>,
    // pub block_height: Option<u64>,
    pub parsed_event_data: AnnotatedMoveStruct,
}
```

1. Should we include the `tx_hash` in the Event? If needed, we should record the tx_hash with Event in the EventStore.
2. Should we include the `timestamp_ms` and when to fill the timestamp?
3. `parsed_event_data` is not unified with other `Annotated` structs.  

I suggest removing the `tx_hash` and `timestamp`, making the `Event` a pure event.

@baichuan3 @wow-sven

**Comment by baichuan3** [comment]
ok, I will remove `tx_hash` and `timestamp`, and unify the `parsed_event_data `
