### ISSUE TITLE
Dashboard authorize error 

### ISSUE THREAD

**Issue by Elitexv** [rooch-network/rooch#994]
![IMG_2766](https://github.com/rooch-network/rooch/assets/46462325/c0fd071d-fd33-4c89-b037-80255d5e933c)

1.On clicking Authorize throws,create session  key > Rooch argument type toBIGINT operation 

2 sign in using GitHub doesn’t work for now

**Comment by jolestar** [comment]
Have you tried to connect the dashboard before? 
Use a new address or clean your account nonce data.

<img width="328" alt="Screen Shot 2023-10-19 at 12 25 08" src="https://github.com/rooch-network/rooch/assets/77268/13bb137c-dd56-43aa-ba5a-7b242c248005">

But wait for #996 to be deployed.

**Comment by Elitexv** [comment]
Alright will test that seems the #996 is been deployed I guess?

**Comment by jolestar** [comment]
> Alright will test that seems the #996 is been deployed I guess?

Yes
