### ISSUE TITLE
[Object] Proposal to Introduce Singleton Pattern

### ISSUE THREAD

**Issue by WGB5445** [rooch-network/rooch#995]
After thorough discussion, @jolestar  proposed the Singleton pattern.

When implementing instances of an Object, we want only one instantiated object globally for a specific type of Object.

We can use new_object_with_id to create a singleton instance.

```
let object_id = object::address_to_object_id(
    address::from_bytes(
        hash::blake2b256(
            bcs::to_bytes(
                &type_info::type_of<Object<T>>()
            )
        )
    )
);

let unique_object = context::new_object_with_id( ctx, object_id, owner, value );
```

We will implement the Display as the first example, which will be used in the NFT standard.

#963 

### Singleton Pattern Outside the Framework
However, for the Singleton pattern, the existing address_to_object_id and new_object_with_id functions are part of the Friend struct. 

Therefore, we need a separate struct to implement the Singleton pattern throughout the entire framework.

```
module rooch_framework::singleton_object{
    struct SingletonObject<T: key> has key {
              object: ObjectID
    }
}

```
For a generic Singleton pattern implementation, further discussion may be required.

**Comment by jolestar** [comment]
Is the `SingletonObject` not an `Object`? How about reusing the Object<T> and ObjectRef<T>.

**Comment by WGB5445** [comment]
> Is the `SingletonObject` not an `Object`? How about reusing the Object and ObjectRef.

May be used in the form `Object<SingletonObject<T>>` ?

**Comment by jolestar** [comment]
Object<T> can represent the singleton Object. We just changed the ObjectID generation method.

**Comment by jolestar** [comment]
```move
moveos_std::context{
  
  #[private_generics(T)]
  public fun singleton_object<T>(&mut ctx, T): ObjectRef<T>;
  
  #[private_generics(T)]
  public fun borrow_object<T>(&ctx): &Object<T>{
  }
}
```
